// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dreamsleeve.Protocol.Chat {

  /// <summary>Holder for reflection information generated from protocol.proto</summary>
  public static partial class ProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for protocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5wcm90b2NvbC5wcm90bxIZRHJlYW1zbGVldmUuUHJvdG9jb2wuQ2hhdBoK",
            "Y2hhdC5wcm90bxoNc2Vzc2lvbi5wcm90bxoMcGxheWVyLnByb3RvIs0CCgxD",
            "bGllbnRQYWNrZXQSGAoQcHJvdG9jb2xfdmVyc2lvbhgBIAEoDRISCgpyZXF1",
            "ZXN0X2lkGAIgASgEEj4KDG9wZW5fc2Vzc2lvbhgKIAEoCzImLkRyZWFtc2xl",
            "ZXZlLlByb3RvY29sLkNoYXQuT3BlblNlc3Npb25IABI4CglzZW5kX2NoYXQY",
            "CyABKAsyIy5EcmVhbXNsZWV2ZS5Qcm90b2NvbC5DaGF0LlNlbmRDaGF0SAAS",
            "QAoNdXBkYXRlX3BsYXllchgMIAEoCzInLkRyZWFtc2xlZXZlLlByb3RvY29s",
            "LkNoYXQuVXBkYXRlUGxheWVySAASSAoRcG9zdF9hbm5vdW5jZW1lbnQYDSAB",
            "KAsyKy5EcmVhbXNsZWV2ZS5Qcm90b2NvbC5DaGF0LlBvc3RBbm5vdW5jZW1l",
            "bnRIAEIJCgdwYXlsb2FkIpkGCgxTZXJ2ZXJQYWNrZXQSGAoQcHJvdG9jb2xf",
            "dmVyc2lvbhgBIAEoDRIXCgpyZXF1ZXN0X2lkGAIgASgESAGIAQESQgoOc2Vz",
            "c2lvbl9vcGVuZWQYCiABKAsyKC5EcmVhbXNsZWV2ZS5Qcm90b2NvbC5DaGF0",
            "LlNlc3Npb25PcGVuZWRIABJCCg5jaGF0X3B1Ymxpc2hlZBgLIAEoCzIoLkRy",
            "ZWFtc2xlZXZlLlByb3RvY29sLkNoYXQuQ2hhdFB1Ymxpc2hlZEgAEkYKEHJl",
            "cXVlc3RfcmVqZWN0ZWQYDCABKAsyKi5EcmVhbXNsZWV2ZS5Qcm90b2NvbC5D",
            "aGF0LlJlcXVlc3RSZWplY3RlZEgAEkAKDXBsYXllcl9qb2luZWQYDSABKAsy",
            "Jy5EcmVhbXNsZWV2ZS5Qcm90b2NvbC5DaGF0LlBsYXllckpvaW5lZEgAEjwK",
            "C3BsYXllcl9sZWZ0GA4gASgLMiUuRHJlYW1zbGVldmUuUHJvdG9jb2wuQ2hh",
            "dC5QbGF5ZXJMZWZ0SAASQgoOcGxheWVyX3VwZGF0ZWQYDyABKAsyKC5EcmVh",
            "bXNsZWV2ZS5Qcm90b2NvbC5DaGF0LlBsYXllclVwZGF0ZWRIABJRChZwbGF5",
            "ZXJfdXBkYXRlX2FjY2VwdGVkGBAgASgLMi8uRHJlYW1zbGVldmUuUHJvdG9j",
            "b2wuQ2hhdC5QbGF5ZXJVcGRhdGVBY2NlcHRlZEgAElcKGXBsYXllcl92aXNp",
            "YmlsaXR5X2NoYW5nZWQYFCABKAsyMi5EcmVhbXNsZWV2ZS5Qcm90b2NvbC5D",
            "aGF0LlBsYXllclZpc2liaWxpdHlDaGFuZ2VkSAASUwoXcGxheWVyX21ldGFk",
            "YXRhX2NoYW5nZWQYEiABKAsyMC5EcmVhbXNsZWV2ZS5Qcm90b2NvbC5DaGF0",
            "LlBsYXllck1ldGFkYXRhQ2hhbmdlZEgAQgkKB3BheWxvYWRCDQoLX3JlcXVl",
            "c3RfaWRKBAgREBJKBAgTEBRSDHBsYXllcl9tb3ZlZFINcGxheWVyc19tb3Zl",
            "ZCIWChRQbGF5ZXJVcGRhdGVBY2NlcHRlZCJwCg9SZXF1ZXN0UmVqZWN0ZWQS",
            "PQoEY29kZRgBIAEoDjIvLkRyZWFtc2xlZXZlLlByb3RvY29sLkNoYXQuUmVx",
            "dWVzdFJlamVjdGlvbkNvZGUSDwoHbWVzc2FnZRgCIAEoCRINCgVmaWVsZBgD",
            "IAEoCSJrChRDbGllbnRNb3ZlbWVudFBhY2tldBIYChBwcm90b2NvbF92ZXJz",
            "aW9uGAEgASgNEjkKBnNhbXBsZRgCIAEoCzIpLkRyZWFtc2xlZXZlLlByb3Rv",
            "Y29sLkNoYXQuTW92ZW1lbnRTYW1wbGUibAoUU2VydmVyTW92ZW1lbnRQYWNr",
            "ZXQSGAoQcHJvdG9jb2xfdmVyc2lvbhgBIAEoDRI6Cgltb3ZlbWVudHMYAiAB",
            "KAsyJy5EcmVhbXNsZWV2ZS5Qcm90b2NvbC5DaGF0LlBsYXllcnNNb3ZlZCq1",
            "BAoUUmVxdWVzdFJlamVjdGlvbkNvZGUSJgoiUkVRVUVTVF9SRUpFQ1RJT05f",
            "Q09ERV9VTlNQRUNJRklFRBAAEioKJlJFUVVFU1RfUkVKRUNUSU9OX0NPREVf",
            "SU5WQUxJRF9SRVFVRVNUEAESLAooUkVRVUVTVF9SRUpFQ1RJT05fQ09ERV9T",
            "RVNTSU9OX05PVF9SRUFEWRACEi8KK1JFUVVFU1RfUkVKRUNUSU9OX0NPREVf",
            "U0VTU0lPTl9BTFJFQURZX09QRU4QAxIpCiVSRVFVRVNUX1JFSkVDVElPTl9D",
            "T0RFX1VTRVJOQU1FX1RBS0VOEAQSLAooUkVRVUVTVF9SRUpFQ1RJT05fQ09E",
            "RV9DSEFOTkVMX05PVF9GT1VORBAFEi0KKVJFUVVFU1RfUkVKRUNUSU9OX0NP",
            "REVfTk9UX0NIQU5ORUxfTUVNQkVSEAYSJQohUkVRVUVTVF9SRUpFQ1RJT05f",
            "Q09ERV9PVkVSTE9BREVEEAcSMAosUkVRVUVTVF9SRUpFQ1RJT05fQ09ERV9B",
            "VVRIRU5USUNBVElPTl9GQUlMRUQQCBIrCidSRVFVRVNUX1JFSkVDVElPTl9D",
            "T0RFX1RFWFRfTk9UX0FMTE9XRUQQCRInCiNSRVFVRVNUX1JFSkVDVElPTl9D",
            "T0RFX1JBVEVfTElNSVRFRBAKEjMKL1JFUVVFU1RfUkVKRUNUSU9OX0NPREVf",
            "QU5OT1VOQ0VNRU5UX05PVF9BTExPV0VEEAtiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dreamsleeve.Protocol.Chat.ChatReflection.Descriptor, global::Dreamsleeve.Protocol.Chat.SessionReflection.Descriptor, global::Dreamsleeve.Protocol.Chat.PlayerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Dreamsleeve.Protocol.Chat.RequestRejectionCode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dreamsleeve.Protocol.Chat.ClientPacket), global::Dreamsleeve.Protocol.Chat.ClientPacket.Parser, new[]{ "ProtocolVersion", "RequestId", "OpenSession", "SendChat", "UpdatePlayer", "PostAnnouncement" }, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dreamsleeve.Protocol.Chat.ServerPacket), global::Dreamsleeve.Protocol.Chat.ServerPacket.Parser, new[]{ "ProtocolVersion", "RequestId", "SessionOpened", "ChatPublished", "RequestRejected", "PlayerJoined", "PlayerLeft", "PlayerUpdated", "PlayerUpdateAccepted", "PlayerVisibilityChanged", "PlayerMetadataChanged" }, new[]{ "Payload", "RequestId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dreamsleeve.Protocol.Chat.PlayerUpdateAccepted), global::Dreamsleeve.Protocol.Chat.PlayerUpdateAccepted.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dreamsleeve.Protocol.Chat.RequestRejected), global::Dreamsleeve.Protocol.Chat.RequestRejected.Parser, new[]{ "Code", "Message", "Field" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dreamsleeve.Protocol.Chat.ClientMovementPacket), global::Dreamsleeve.Protocol.Chat.ClientMovementPacket.Parser, new[]{ "ProtocolVersion", "Sample" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dreamsleeve.Protocol.Chat.ServerMovementPacket), global::Dreamsleeve.Protocol.Chat.ServerMovementPacket.Parser, new[]{ "ProtocolVersion", "Movements" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Stable application rejection codes shared by client and server.
  /// Never reuse numeric values; reserve removed values/names when evolving this enum.
  /// </summary>
  public enum RequestRejectionCode {
    /// <summary>
    /// Invalid in a RequestRejected response.
    /// </summary>
    [pbr::OriginalName("REQUEST_REJECTION_CODE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Invalid field or command arguments.
    /// </summary>
    [pbr::OriginalName("REQUEST_REJECTION_CODE_INVALID_REQUEST")] InvalidRequest = 1,
    /// <summary>
    /// No ready application session.
    /// </summary>
    [pbr::OriginalName("REQUEST_REJECTION_CODE_SESSION_NOT_READY")] SessionNotReady = 2,
    /// <summary>
    /// Repeated OpenSession.
    /// </summary>
    [pbr::OriginalName("REQUEST_REJECTION_CODE_SESSION_ALREADY_OPEN")] SessionAlreadyOpen = 3,
    /// <summary>
    /// Requested username is already reserved.
    /// </summary>
    [pbr::OriginalName("REQUEST_REJECTION_CODE_USERNAME_TAKEN")] UsernameTaken = 4,
    /// <summary>
    /// Requested channel does not exist.
    /// </summary>
    [pbr::OriginalName("REQUEST_REJECTION_CODE_CHANNEL_NOT_FOUND")] ChannelNotFound = 5,
    /// <summary>
    /// Sender may not publish to this channel.
    /// </summary>
    [pbr::OriginalName("REQUEST_REJECTION_CODE_NOT_CHANNEL_MEMBER")] NotChannelMember = 6,
    /// <summary>
    /// Request was not admitted; the session remains usable.
    /// </summary>
    [pbr::OriginalName("REQUEST_REJECTION_CODE_OVERLOADED")] Overloaded = 7,
    /// <summary>
    /// Missing, expired, invalid or already consumed ticket.
    /// </summary>
    [pbr::OriginalName("REQUEST_REJECTION_CODE_AUTHENTICATION_FAILED")] AuthenticationFailed = 8,
    /// <summary>
    /// Text matched the server word list.
    /// </summary>
    [pbr::OriginalName("REQUEST_REJECTION_CODE_TEXT_NOT_ALLOWED")] TextNotAllowed = 9,
    /// <summary>
    /// Too frequent or repeated; retry later.
    /// </summary>
    [pbr::OriginalName("REQUEST_REJECTION_CODE_RATE_LIMITED")] RateLimited = 10,
    /// <summary>
    /// The server does not accept this announcement source.
    /// </summary>
    [pbr::OriginalName("REQUEST_REJECTION_CODE_ANNOUNCEMENT_NOT_ALLOWED")] AnnouncementNotAllowed = 11,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Control/chat envelope. Version 6 separates repeated realtime poses from reliable commands. Opens sessions
  /// with a single-use ticket issued by the separate authenticated HTTP endpoint. A session belongs to one ENet connection; opening it again
  /// requires reconnecting. Transport Connected alone is not application readiness.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClientPacket : pb::IMessage<ClientPacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientPacket> _parser = new pb::MessageParser<ClientPacket>(() => new ClientPacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClientPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dreamsleeve.Protocol.Chat.ProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientPacket(ClientPacket other) : this() {
      protocolVersion_ = other.protocolVersion_;
      requestId_ = other.requestId_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.OpenSession:
          OpenSession = other.OpenSession.Clone();
          break;
        case PayloadOneofCase.SendChat:
          SendChat = other.SendChat.Clone();
          break;
        case PayloadOneofCase.UpdatePlayer:
          UpdatePlayer = other.UpdatePlayer.Clone();
          break;
        case PayloadOneofCase.PostAnnouncement:
          PostAnnouncement = other.PostAnnouncement.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientPacket Clone() {
      return new ClientPacket(this);
    }

    /// <summary>Field number for the "protocol_version" field.</summary>
    public const int ProtocolVersionFieldNumber = 1;
    private uint protocolVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ProtocolVersion {
      get { return protocolVersion_; }
      set {
        protocolVersion_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 2;
    private ulong requestId_;
    /// <summary>
    /// Nonzero, assigned by the initiating client.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RequestId {
      get { return requestId_; }
      set {
        requestId_ = value;
      }
    }

    /// <summary>Field number for the "open_session" field.</summary>
    public const int OpenSessionFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.OpenSession OpenSession {
      get { return payloadCase_ == PayloadOneofCase.OpenSession ? (global::Dreamsleeve.Protocol.Chat.OpenSession) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.OpenSession;
      }
    }

    /// <summary>Field number for the "send_chat" field.</summary>
    public const int SendChatFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.SendChat SendChat {
      get { return payloadCase_ == PayloadOneofCase.SendChat ? (global::Dreamsleeve.Protocol.Chat.SendChat) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.SendChat;
      }
    }

    /// <summary>Field number for the "update_player" field.</summary>
    public const int UpdatePlayerFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.UpdatePlayer UpdatePlayer {
      get { return payloadCase_ == PayloadOneofCase.UpdatePlayer ? (global::Dreamsleeve.Protocol.Chat.UpdatePlayer) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.UpdatePlayer;
      }
    }

    /// <summary>Field number for the "post_announcement" field.</summary>
    public const int PostAnnouncementFieldNumber = 13;
    /// <summary>
    /// Chat lane, like SendChat.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.PostAnnouncement PostAnnouncement {
      get { return payloadCase_ == PayloadOneofCase.PostAnnouncement ? (global::Dreamsleeve.Protocol.Chat.PostAnnouncement) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.PostAnnouncement;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      OpenSession = 10,
      SendChat = 11,
      UpdatePlayer = 12,
      PostAnnouncement = 13,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClientPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClientPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProtocolVersion != other.ProtocolVersion) return false;
      if (RequestId != other.RequestId) return false;
      if (!object.Equals(OpenSession, other.OpenSession)) return false;
      if (!object.Equals(SendChat, other.SendChat)) return false;
      if (!object.Equals(UpdatePlayer, other.UpdatePlayer)) return false;
      if (!object.Equals(PostAnnouncement, other.PostAnnouncement)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProtocolVersion != 0) hash ^= ProtocolVersion.GetHashCode();
      if (RequestId != 0UL) hash ^= RequestId.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.OpenSession) hash ^= OpenSession.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.SendChat) hash ^= SendChat.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.UpdatePlayer) hash ^= UpdatePlayer.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.PostAnnouncement) hash ^= PostAnnouncement.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProtocolVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ProtocolVersion);
      }
      if (RequestId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(RequestId);
      }
      if (payloadCase_ == PayloadOneofCase.OpenSession) {
        output.WriteRawTag(82);
        output.WriteMessage(OpenSession);
      }
      if (payloadCase_ == PayloadOneofCase.SendChat) {
        output.WriteRawTag(90);
        output.WriteMessage(SendChat);
      }
      if (payloadCase_ == PayloadOneofCase.UpdatePlayer) {
        output.WriteRawTag(98);
        output.WriteMessage(UpdatePlayer);
      }
      if (payloadCase_ == PayloadOneofCase.PostAnnouncement) {
        output.WriteRawTag(106);
        output.WriteMessage(PostAnnouncement);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProtocolVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ProtocolVersion);
      }
      if (RequestId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(RequestId);
      }
      if (payloadCase_ == PayloadOneofCase.OpenSession) {
        output.WriteRawTag(82);
        output.WriteMessage(OpenSession);
      }
      if (payloadCase_ == PayloadOneofCase.SendChat) {
        output.WriteRawTag(90);
        output.WriteMessage(SendChat);
      }
      if (payloadCase_ == PayloadOneofCase.UpdatePlayer) {
        output.WriteRawTag(98);
        output.WriteMessage(UpdatePlayer);
      }
      if (payloadCase_ == PayloadOneofCase.PostAnnouncement) {
        output.WriteRawTag(106);
        output.WriteMessage(PostAnnouncement);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProtocolVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProtocolVersion);
      }
      if (RequestId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RequestId);
      }
      if (payloadCase_ == PayloadOneofCase.OpenSession) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OpenSession);
      }
      if (payloadCase_ == PayloadOneofCase.SendChat) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SendChat);
      }
      if (payloadCase_ == PayloadOneofCase.UpdatePlayer) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdatePlayer);
      }
      if (payloadCase_ == PayloadOneofCase.PostAnnouncement) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PostAnnouncement);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClientPacket other) {
      if (other == null) {
        return;
      }
      if (other.ProtocolVersion != 0) {
        ProtocolVersion = other.ProtocolVersion;
      }
      if (other.RequestId != 0UL) {
        RequestId = other.RequestId;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.OpenSession:
          if (OpenSession == null) {
            OpenSession = new global::Dreamsleeve.Protocol.Chat.OpenSession();
          }
          OpenSession.MergeFrom(other.OpenSession);
          break;
        case PayloadOneofCase.SendChat:
          if (SendChat == null) {
            SendChat = new global::Dreamsleeve.Protocol.Chat.SendChat();
          }
          SendChat.MergeFrom(other.SendChat);
          break;
        case PayloadOneofCase.UpdatePlayer:
          if (UpdatePlayer == null) {
            UpdatePlayer = new global::Dreamsleeve.Protocol.Chat.UpdatePlayer();
          }
          UpdatePlayer.MergeFrom(other.UpdatePlayer);
          break;
        case PayloadOneofCase.PostAnnouncement:
          if (PostAnnouncement == null) {
            PostAnnouncement = new global::Dreamsleeve.Protocol.Chat.PostAnnouncement();
          }
          PostAnnouncement.MergeFrom(other.PostAnnouncement);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProtocolVersion = input.ReadUInt32();
            break;
          }
          case 16: {
            RequestId = input.ReadUInt64();
            break;
          }
          case 82: {
            global::Dreamsleeve.Protocol.Chat.OpenSession subBuilder = new global::Dreamsleeve.Protocol.Chat.OpenSession();
            if (payloadCase_ == PayloadOneofCase.OpenSession) {
              subBuilder.MergeFrom(OpenSession);
            }
            input.ReadMessage(subBuilder);
            OpenSession = subBuilder;
            break;
          }
          case 90: {
            global::Dreamsleeve.Protocol.Chat.SendChat subBuilder = new global::Dreamsleeve.Protocol.Chat.SendChat();
            if (payloadCase_ == PayloadOneofCase.SendChat) {
              subBuilder.MergeFrom(SendChat);
            }
            input.ReadMessage(subBuilder);
            SendChat = subBuilder;
            break;
          }
          case 98: {
            global::Dreamsleeve.Protocol.Chat.UpdatePlayer subBuilder = new global::Dreamsleeve.Protocol.Chat.UpdatePlayer();
            if (payloadCase_ == PayloadOneofCase.UpdatePlayer) {
              subBuilder.MergeFrom(UpdatePlayer);
            }
            input.ReadMessage(subBuilder);
            UpdatePlayer = subBuilder;
            break;
          }
          case 106: {
            global::Dreamsleeve.Protocol.Chat.PostAnnouncement subBuilder = new global::Dreamsleeve.Protocol.Chat.PostAnnouncement();
            if (payloadCase_ == PayloadOneofCase.PostAnnouncement) {
              subBuilder.MergeFrom(PostAnnouncement);
            }
            input.ReadMessage(subBuilder);
            PostAnnouncement = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProtocolVersion = input.ReadUInt32();
            break;
          }
          case 16: {
            RequestId = input.ReadUInt64();
            break;
          }
          case 82: {
            global::Dreamsleeve.Protocol.Chat.OpenSession subBuilder = new global::Dreamsleeve.Protocol.Chat.OpenSession();
            if (payloadCase_ == PayloadOneofCase.OpenSession) {
              subBuilder.MergeFrom(OpenSession);
            }
            input.ReadMessage(subBuilder);
            OpenSession = subBuilder;
            break;
          }
          case 90: {
            global::Dreamsleeve.Protocol.Chat.SendChat subBuilder = new global::Dreamsleeve.Protocol.Chat.SendChat();
            if (payloadCase_ == PayloadOneofCase.SendChat) {
              subBuilder.MergeFrom(SendChat);
            }
            input.ReadMessage(subBuilder);
            SendChat = subBuilder;
            break;
          }
          case 98: {
            global::Dreamsleeve.Protocol.Chat.UpdatePlayer subBuilder = new global::Dreamsleeve.Protocol.Chat.UpdatePlayer();
            if (payloadCase_ == PayloadOneofCase.UpdatePlayer) {
              subBuilder.MergeFrom(UpdatePlayer);
            }
            input.ReadMessage(subBuilder);
            UpdatePlayer = subBuilder;
            break;
          }
          case 106: {
            global::Dreamsleeve.Protocol.Chat.PostAnnouncement subBuilder = new global::Dreamsleeve.Protocol.Chat.PostAnnouncement();
            if (payloadCase_ == PayloadOneofCase.PostAnnouncement) {
              subBuilder.MergeFrom(PostAnnouncement);
            }
            input.ReadMessage(subBuilder);
            PostAnnouncement = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Correlation is recipient-specific. A chat broadcast includes request_id only
  /// in the copy sent to its initiating connection. Others receive the same message
  /// without request_id and apply it through the same state-update path.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ServerPacket : pb::IMessage<ServerPacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServerPacket> _parser = new pb::MessageParser<ServerPacket>(() => new ServerPacket());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServerPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dreamsleeve.Protocol.Chat.ProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerPacket(ServerPacket other) : this() {
      _hasBits0 = other._hasBits0;
      protocolVersion_ = other.protocolVersion_;
      requestId_ = other.requestId_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.SessionOpened:
          SessionOpened = other.SessionOpened.Clone();
          break;
        case PayloadOneofCase.ChatPublished:
          ChatPublished = other.ChatPublished.Clone();
          break;
        case PayloadOneofCase.RequestRejected:
          RequestRejected = other.RequestRejected.Clone();
          break;
        case PayloadOneofCase.PlayerJoined:
          PlayerJoined = other.PlayerJoined.Clone();
          break;
        case PayloadOneofCase.PlayerLeft:
          PlayerLeft = other.PlayerLeft.Clone();
          break;
        case PayloadOneofCase.PlayerUpdated:
          PlayerUpdated = other.PlayerUpdated.Clone();
          break;
        case PayloadOneofCase.PlayerUpdateAccepted:
          PlayerUpdateAccepted = other.PlayerUpdateAccepted.Clone();
          break;
        case PayloadOneofCase.PlayerVisibilityChanged:
          PlayerVisibilityChanged = other.PlayerVisibilityChanged.Clone();
          break;
        case PayloadOneofCase.PlayerMetadataChanged:
          PlayerMetadataChanged = other.PlayerMetadataChanged.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerPacket Clone() {
      return new ServerPacket(this);
    }

    /// <summary>Field number for the "protocol_version" field.</summary>
    public const int ProtocolVersionFieldNumber = 1;
    private uint protocolVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ProtocolVersion {
      get { return protocolVersion_; }
      set {
        protocolVersion_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 2;
    private readonly static ulong RequestIdDefaultValue = 0UL;

    private ulong requestId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RequestId {
      get { if ((_hasBits0 & 1) != 0) { return requestId_; } else { return RequestIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        requestId_ = value;
      }
    }
    /// <summary>Gets whether the "request_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRequestId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "request_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRequestId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "session_opened" field.</summary>
    public const int SessionOpenedFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.SessionOpened SessionOpened {
      get { return payloadCase_ == PayloadOneofCase.SessionOpened ? (global::Dreamsleeve.Protocol.Chat.SessionOpened) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.SessionOpened;
      }
    }

    /// <summary>Field number for the "chat_published" field.</summary>
    public const int ChatPublishedFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.ChatPublished ChatPublished {
      get { return payloadCase_ == PayloadOneofCase.ChatPublished ? (global::Dreamsleeve.Protocol.Chat.ChatPublished) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ChatPublished;
      }
    }

    /// <summary>Field number for the "request_rejected" field.</summary>
    public const int RequestRejectedFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.RequestRejected RequestRejected {
      get { return payloadCase_ == PayloadOneofCase.RequestRejected ? (global::Dreamsleeve.Protocol.Chat.RequestRejected) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.RequestRejected;
      }
    }

    /// <summary>Field number for the "player_joined" field.</summary>
    public const int PlayerJoinedFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.PlayerJoined PlayerJoined {
      get { return payloadCase_ == PayloadOneofCase.PlayerJoined ? (global::Dreamsleeve.Protocol.Chat.PlayerJoined) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.PlayerJoined;
      }
    }

    /// <summary>Field number for the "player_left" field.</summary>
    public const int PlayerLeftFieldNumber = 14;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.PlayerLeft PlayerLeft {
      get { return payloadCase_ == PayloadOneofCase.PlayerLeft ? (global::Dreamsleeve.Protocol.Chat.PlayerLeft) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.PlayerLeft;
      }
    }

    /// <summary>Field number for the "player_updated" field.</summary>
    public const int PlayerUpdatedFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.PlayerUpdated PlayerUpdated {
      get { return payloadCase_ == PayloadOneofCase.PlayerUpdated ? (global::Dreamsleeve.Protocol.Chat.PlayerUpdated) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.PlayerUpdated;
      }
    }

    /// <summary>Field number for the "player_update_accepted" field.</summary>
    public const int PlayerUpdateAcceptedFieldNumber = 16;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.PlayerUpdateAccepted PlayerUpdateAccepted {
      get { return payloadCase_ == PayloadOneofCase.PlayerUpdateAccepted ? (global::Dreamsleeve.Protocol.Chat.PlayerUpdateAccepted) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.PlayerUpdateAccepted;
      }
    }

    /// <summary>Field number for the "player_visibility_changed" field.</summary>
    public const int PlayerVisibilityChangedFieldNumber = 20;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.PlayerVisibilityChanged PlayerVisibilityChanged {
      get { return payloadCase_ == PayloadOneofCase.PlayerVisibilityChanged ? (global::Dreamsleeve.Protocol.Chat.PlayerVisibilityChanged) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.PlayerVisibilityChanged;
      }
    }

    /// <summary>Field number for the "player_metadata_changed" field.</summary>
    public const int PlayerMetadataChangedFieldNumber = 18;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.PlayerMetadataChanged PlayerMetadataChanged {
      get { return payloadCase_ == PayloadOneofCase.PlayerMetadataChanged ? (global::Dreamsleeve.Protocol.Chat.PlayerMetadataChanged) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.PlayerMetadataChanged;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      SessionOpened = 10,
      ChatPublished = 11,
      RequestRejected = 12,
      PlayerJoined = 13,
      PlayerLeft = 14,
      PlayerUpdated = 15,
      PlayerUpdateAccepted = 16,
      PlayerVisibilityChanged = 20,
      PlayerMetadataChanged = 18,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServerPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServerPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProtocolVersion != other.ProtocolVersion) return false;
      if (RequestId != other.RequestId) return false;
      if (!object.Equals(SessionOpened, other.SessionOpened)) return false;
      if (!object.Equals(ChatPublished, other.ChatPublished)) return false;
      if (!object.Equals(RequestRejected, other.RequestRejected)) return false;
      if (!object.Equals(PlayerJoined, other.PlayerJoined)) return false;
      if (!object.Equals(PlayerLeft, other.PlayerLeft)) return false;
      if (!object.Equals(PlayerUpdated, other.PlayerUpdated)) return false;
      if (!object.Equals(PlayerUpdateAccepted, other.PlayerUpdateAccepted)) return false;
      if (!object.Equals(PlayerVisibilityChanged, other.PlayerVisibilityChanged)) return false;
      if (!object.Equals(PlayerMetadataChanged, other.PlayerMetadataChanged)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProtocolVersion != 0) hash ^= ProtocolVersion.GetHashCode();
      if (HasRequestId) hash ^= RequestId.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.SessionOpened) hash ^= SessionOpened.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ChatPublished) hash ^= ChatPublished.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.RequestRejected) hash ^= RequestRejected.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.PlayerJoined) hash ^= PlayerJoined.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.PlayerLeft) hash ^= PlayerLeft.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.PlayerUpdated) hash ^= PlayerUpdated.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.PlayerUpdateAccepted) hash ^= PlayerUpdateAccepted.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.PlayerVisibilityChanged) hash ^= PlayerVisibilityChanged.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.PlayerMetadataChanged) hash ^= PlayerMetadataChanged.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProtocolVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ProtocolVersion);
      }
      if (HasRequestId) {
        output.WriteRawTag(16);
        output.WriteUInt64(RequestId);
      }
      if (payloadCase_ == PayloadOneofCase.SessionOpened) {
        output.WriteRawTag(82);
        output.WriteMessage(SessionOpened);
      }
      if (payloadCase_ == PayloadOneofCase.ChatPublished) {
        output.WriteRawTag(90);
        output.WriteMessage(ChatPublished);
      }
      if (payloadCase_ == PayloadOneofCase.RequestRejected) {
        output.WriteRawTag(98);
        output.WriteMessage(RequestRejected);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerJoined) {
        output.WriteRawTag(106);
        output.WriteMessage(PlayerJoined);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerLeft) {
        output.WriteRawTag(114);
        output.WriteMessage(PlayerLeft);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerUpdated) {
        output.WriteRawTag(122);
        output.WriteMessage(PlayerUpdated);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerUpdateAccepted) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(PlayerUpdateAccepted);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerMetadataChanged) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(PlayerMetadataChanged);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerVisibilityChanged) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(PlayerVisibilityChanged);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProtocolVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ProtocolVersion);
      }
      if (HasRequestId) {
        output.WriteRawTag(16);
        output.WriteUInt64(RequestId);
      }
      if (payloadCase_ == PayloadOneofCase.SessionOpened) {
        output.WriteRawTag(82);
        output.WriteMessage(SessionOpened);
      }
      if (payloadCase_ == PayloadOneofCase.ChatPublished) {
        output.WriteRawTag(90);
        output.WriteMessage(ChatPublished);
      }
      if (payloadCase_ == PayloadOneofCase.RequestRejected) {
        output.WriteRawTag(98);
        output.WriteMessage(RequestRejected);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerJoined) {
        output.WriteRawTag(106);
        output.WriteMessage(PlayerJoined);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerLeft) {
        output.WriteRawTag(114);
        output.WriteMessage(PlayerLeft);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerUpdated) {
        output.WriteRawTag(122);
        output.WriteMessage(PlayerUpdated);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerUpdateAccepted) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(PlayerUpdateAccepted);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerMetadataChanged) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(PlayerMetadataChanged);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerVisibilityChanged) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(PlayerVisibilityChanged);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProtocolVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProtocolVersion);
      }
      if (HasRequestId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RequestId);
      }
      if (payloadCase_ == PayloadOneofCase.SessionOpened) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SessionOpened);
      }
      if (payloadCase_ == PayloadOneofCase.ChatPublished) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatPublished);
      }
      if (payloadCase_ == PayloadOneofCase.RequestRejected) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RequestRejected);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerJoined) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerJoined);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerLeft) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerLeft);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerUpdated) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerUpdated);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerUpdateAccepted) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PlayerUpdateAccepted);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerVisibilityChanged) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PlayerVisibilityChanged);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerMetadataChanged) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PlayerMetadataChanged);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServerPacket other) {
      if (other == null) {
        return;
      }
      if (other.ProtocolVersion != 0) {
        ProtocolVersion = other.ProtocolVersion;
      }
      if (other.HasRequestId) {
        RequestId = other.RequestId;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.SessionOpened:
          if (SessionOpened == null) {
            SessionOpened = new global::Dreamsleeve.Protocol.Chat.SessionOpened();
          }
          SessionOpened.MergeFrom(other.SessionOpened);
          break;
        case PayloadOneofCase.ChatPublished:
          if (ChatPublished == null) {
            ChatPublished = new global::Dreamsleeve.Protocol.Chat.ChatPublished();
          }
          ChatPublished.MergeFrom(other.ChatPublished);
          break;
        case PayloadOneofCase.RequestRejected:
          if (RequestRejected == null) {
            RequestRejected = new global::Dreamsleeve.Protocol.Chat.RequestRejected();
          }
          RequestRejected.MergeFrom(other.RequestRejected);
          break;
        case PayloadOneofCase.PlayerJoined:
          if (PlayerJoined == null) {
            PlayerJoined = new global::Dreamsleeve.Protocol.Chat.PlayerJoined();
          }
          PlayerJoined.MergeFrom(other.PlayerJoined);
          break;
        case PayloadOneofCase.PlayerLeft:
          if (PlayerLeft == null) {
            PlayerLeft = new global::Dreamsleeve.Protocol.Chat.PlayerLeft();
          }
          PlayerLeft.MergeFrom(other.PlayerLeft);
          break;
        case PayloadOneofCase.PlayerUpdated:
          if (PlayerUpdated == null) {
            PlayerUpdated = new global::Dreamsleeve.Protocol.Chat.PlayerUpdated();
          }
          PlayerUpdated.MergeFrom(other.PlayerUpdated);
          break;
        case PayloadOneofCase.PlayerUpdateAccepted:
          if (PlayerUpdateAccepted == null) {
            PlayerUpdateAccepted = new global::Dreamsleeve.Protocol.Chat.PlayerUpdateAccepted();
          }
          PlayerUpdateAccepted.MergeFrom(other.PlayerUpdateAccepted);
          break;
        case PayloadOneofCase.PlayerVisibilityChanged:
          if (PlayerVisibilityChanged == null) {
            PlayerVisibilityChanged = new global::Dreamsleeve.Protocol.Chat.PlayerVisibilityChanged();
          }
          PlayerVisibilityChanged.MergeFrom(other.PlayerVisibilityChanged);
          break;
        case PayloadOneofCase.PlayerMetadataChanged:
          if (PlayerMetadataChanged == null) {
            PlayerMetadataChanged = new global::Dreamsleeve.Protocol.Chat.PlayerMetadataChanged();
          }
          PlayerMetadataChanged.MergeFrom(other.PlayerMetadataChanged);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProtocolVersion = input.ReadUInt32();
            break;
          }
          case 16: {
            RequestId = input.ReadUInt64();
            break;
          }
          case 82: {
            global::Dreamsleeve.Protocol.Chat.SessionOpened subBuilder = new global::Dreamsleeve.Protocol.Chat.SessionOpened();
            if (payloadCase_ == PayloadOneofCase.SessionOpened) {
              subBuilder.MergeFrom(SessionOpened);
            }
            input.ReadMessage(subBuilder);
            SessionOpened = subBuilder;
            break;
          }
          case 90: {
            global::Dreamsleeve.Protocol.Chat.ChatPublished subBuilder = new global::Dreamsleeve.Protocol.Chat.ChatPublished();
            if (payloadCase_ == PayloadOneofCase.ChatPublished) {
              subBuilder.MergeFrom(ChatPublished);
            }
            input.ReadMessage(subBuilder);
            ChatPublished = subBuilder;
            break;
          }
          case 98: {
            global::Dreamsleeve.Protocol.Chat.RequestRejected subBuilder = new global::Dreamsleeve.Protocol.Chat.RequestRejected();
            if (payloadCase_ == PayloadOneofCase.RequestRejected) {
              subBuilder.MergeFrom(RequestRejected);
            }
            input.ReadMessage(subBuilder);
            RequestRejected = subBuilder;
            break;
          }
          case 106: {
            global::Dreamsleeve.Protocol.Chat.PlayerJoined subBuilder = new global::Dreamsleeve.Protocol.Chat.PlayerJoined();
            if (payloadCase_ == PayloadOneofCase.PlayerJoined) {
              subBuilder.MergeFrom(PlayerJoined);
            }
            input.ReadMessage(subBuilder);
            PlayerJoined = subBuilder;
            break;
          }
          case 114: {
            global::Dreamsleeve.Protocol.Chat.PlayerLeft subBuilder = new global::Dreamsleeve.Protocol.Chat.PlayerLeft();
            if (payloadCase_ == PayloadOneofCase.PlayerLeft) {
              subBuilder.MergeFrom(PlayerLeft);
            }
            input.ReadMessage(subBuilder);
            PlayerLeft = subBuilder;
            break;
          }
          case 122: {
            global::Dreamsleeve.Protocol.Chat.PlayerUpdated subBuilder = new global::Dreamsleeve.Protocol.Chat.PlayerUpdated();
            if (payloadCase_ == PayloadOneofCase.PlayerUpdated) {
              subBuilder.MergeFrom(PlayerUpdated);
            }
            input.ReadMessage(subBuilder);
            PlayerUpdated = subBuilder;
            break;
          }
          case 130: {
            global::Dreamsleeve.Protocol.Chat.PlayerUpdateAccepted subBuilder = new global::Dreamsleeve.Protocol.Chat.PlayerUpdateAccepted();
            if (payloadCase_ == PayloadOneofCase.PlayerUpdateAccepted) {
              subBuilder.MergeFrom(PlayerUpdateAccepted);
            }
            input.ReadMessage(subBuilder);
            PlayerUpdateAccepted = subBuilder;
            break;
          }
          case 146: {
            global::Dreamsleeve.Protocol.Chat.PlayerMetadataChanged subBuilder = new global::Dreamsleeve.Protocol.Chat.PlayerMetadataChanged();
            if (payloadCase_ == PayloadOneofCase.PlayerMetadataChanged) {
              subBuilder.MergeFrom(PlayerMetadataChanged);
            }
            input.ReadMessage(subBuilder);
            PlayerMetadataChanged = subBuilder;
            break;
          }
          case 162: {
            global::Dreamsleeve.Protocol.Chat.PlayerVisibilityChanged subBuilder = new global::Dreamsleeve.Protocol.Chat.PlayerVisibilityChanged();
            if (payloadCase_ == PayloadOneofCase.PlayerVisibilityChanged) {
              subBuilder.MergeFrom(PlayerVisibilityChanged);
            }
            input.ReadMessage(subBuilder);
            PlayerVisibilityChanged = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProtocolVersion = input.ReadUInt32();
            break;
          }
          case 16: {
            RequestId = input.ReadUInt64();
            break;
          }
          case 82: {
            global::Dreamsleeve.Protocol.Chat.SessionOpened subBuilder = new global::Dreamsleeve.Protocol.Chat.SessionOpened();
            if (payloadCase_ == PayloadOneofCase.SessionOpened) {
              subBuilder.MergeFrom(SessionOpened);
            }
            input.ReadMessage(subBuilder);
            SessionOpened = subBuilder;
            break;
          }
          case 90: {
            global::Dreamsleeve.Protocol.Chat.ChatPublished subBuilder = new global::Dreamsleeve.Protocol.Chat.ChatPublished();
            if (payloadCase_ == PayloadOneofCase.ChatPublished) {
              subBuilder.MergeFrom(ChatPublished);
            }
            input.ReadMessage(subBuilder);
            ChatPublished = subBuilder;
            break;
          }
          case 98: {
            global::Dreamsleeve.Protocol.Chat.RequestRejected subBuilder = new global::Dreamsleeve.Protocol.Chat.RequestRejected();
            if (payloadCase_ == PayloadOneofCase.RequestRejected) {
              subBuilder.MergeFrom(RequestRejected);
            }
            input.ReadMessage(subBuilder);
            RequestRejected = subBuilder;
            break;
          }
          case 106: {
            global::Dreamsleeve.Protocol.Chat.PlayerJoined subBuilder = new global::Dreamsleeve.Protocol.Chat.PlayerJoined();
            if (payloadCase_ == PayloadOneofCase.PlayerJoined) {
              subBuilder.MergeFrom(PlayerJoined);
            }
            input.ReadMessage(subBuilder);
            PlayerJoined = subBuilder;
            break;
          }
          case 114: {
            global::Dreamsleeve.Protocol.Chat.PlayerLeft subBuilder = new global::Dreamsleeve.Protocol.Chat.PlayerLeft();
            if (payloadCase_ == PayloadOneofCase.PlayerLeft) {
              subBuilder.MergeFrom(PlayerLeft);
            }
            input.ReadMessage(subBuilder);
            PlayerLeft = subBuilder;
            break;
          }
          case 122: {
            global::Dreamsleeve.Protocol.Chat.PlayerUpdated subBuilder = new global::Dreamsleeve.Protocol.Chat.PlayerUpdated();
            if (payloadCase_ == PayloadOneofCase.PlayerUpdated) {
              subBuilder.MergeFrom(PlayerUpdated);
            }
            input.ReadMessage(subBuilder);
            PlayerUpdated = subBuilder;
            break;
          }
          case 130: {
            global::Dreamsleeve.Protocol.Chat.PlayerUpdateAccepted subBuilder = new global::Dreamsleeve.Protocol.Chat.PlayerUpdateAccepted();
            if (payloadCase_ == PayloadOneofCase.PlayerUpdateAccepted) {
              subBuilder.MergeFrom(PlayerUpdateAccepted);
            }
            input.ReadMessage(subBuilder);
            PlayerUpdateAccepted = subBuilder;
            break;
          }
          case 146: {
            global::Dreamsleeve.Protocol.Chat.PlayerMetadataChanged subBuilder = new global::Dreamsleeve.Protocol.Chat.PlayerMetadataChanged();
            if (payloadCase_ == PayloadOneofCase.PlayerMetadataChanged) {
              subBuilder.MergeFrom(PlayerMetadataChanged);
            }
            input.ReadMessage(subBuilder);
            PlayerMetadataChanged = subBuilder;
            break;
          }
          case 162: {
            global::Dreamsleeve.Protocol.Chat.PlayerVisibilityChanged subBuilder = new global::Dreamsleeve.Protocol.Chat.PlayerVisibilityChanged();
            if (payloadCase_ == PayloadOneofCase.PlayerVisibilityChanged) {
              subBuilder.MergeFrom(PlayerVisibilityChanged);
            }
            input.ReadMessage(subBuilder);
            PlayerVisibilityChanged = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Settles the command; authoritative state arrives through periodic replication.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerUpdateAccepted : pb::IMessage<PlayerUpdateAccepted>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerUpdateAccepted> _parser = new pb::MessageParser<PlayerUpdateAccepted>(() => new PlayerUpdateAccepted());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerUpdateAccepted> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dreamsleeve.Protocol.Chat.ProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerUpdateAccepted() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerUpdateAccepted(PlayerUpdateAccepted other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerUpdateAccepted Clone() {
      return new PlayerUpdateAccepted(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerUpdateAccepted);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerUpdateAccepted other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerUpdateAccepted other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Code controls program behavior; message is a display/diagnostic fallback.
  /// Clients preserve unknown nonzero codes from newer servers with their message.
  /// request_id in the envelope is mandatory for this first command-response slice.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RequestRejected : pb::IMessage<RequestRejected>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequestRejected> _parser = new pb::MessageParser<RequestRejected>(() => new RequestRejected());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RequestRejected> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dreamsleeve.Protocol.Chat.ProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestRejected() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestRejected(RequestRejected other) : this() {
      code_ = other.code_;
      message_ = other.message_;
      field_ = other.field_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestRejected Clone() {
      return new RequestRejected(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private global::Dreamsleeve.Protocol.Chat.RequestRejectionCode code_ = global::Dreamsleeve.Protocol.Chat.RequestRejectionCode.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.RequestRejectionCode Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "field" field.</summary>
    public const int FieldFieldNumber = 3;
    private string field_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Field {
      get { return field_; }
      set {
        field_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RequestRejected);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RequestRejected other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Message != other.Message) return false;
      if (Field != other.Field) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != global::Dreamsleeve.Protocol.Chat.RequestRejectionCode.Unspecified) hash ^= Code.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Field.Length != 0) hash ^= Field.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Code != global::Dreamsleeve.Protocol.Chat.RequestRejectionCode.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Field.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Field);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Code != global::Dreamsleeve.Protocol.Chat.RequestRejectionCode.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Field.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Field);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Code != global::Dreamsleeve.Protocol.Chat.RequestRejectionCode.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Field.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Field);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RequestRejected other) {
      if (other == null) {
        return;
      }
      if (other.Code != global::Dreamsleeve.Protocol.Chat.RequestRejectionCode.Unspecified) {
        Code = other.Code;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Field.Length != 0) {
        Field = other.Field;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = (global::Dreamsleeve.Protocol.Chat.RequestRejectionCode) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 26: {
            Field = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = (global::Dreamsleeve.Protocol.Chat.RequestRejectionCode) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 26: {
            Field = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Realtime channel: no request correlation or per-sample acceptance.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClientMovementPacket : pb::IMessage<ClientMovementPacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClientMovementPacket> _parser = new pb::MessageParser<ClientMovementPacket>(() => new ClientMovementPacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClientMovementPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dreamsleeve.Protocol.Chat.ProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientMovementPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientMovementPacket(ClientMovementPacket other) : this() {
      protocolVersion_ = other.protocolVersion_;
      sample_ = other.sample_ != null ? other.sample_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClientMovementPacket Clone() {
      return new ClientMovementPacket(this);
    }

    /// <summary>Field number for the "protocol_version" field.</summary>
    public const int ProtocolVersionFieldNumber = 1;
    private uint protocolVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ProtocolVersion {
      get { return protocolVersion_; }
      set {
        protocolVersion_ = value;
      }
    }

    /// <summary>Field number for the "sample" field.</summary>
    public const int SampleFieldNumber = 2;
    private global::Dreamsleeve.Protocol.Chat.MovementSample sample_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.MovementSample Sample {
      get { return sample_; }
      set {
        sample_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClientMovementPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClientMovementPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProtocolVersion != other.ProtocolVersion) return false;
      if (!object.Equals(Sample, other.Sample)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProtocolVersion != 0) hash ^= ProtocolVersion.GetHashCode();
      if (sample_ != null) hash ^= Sample.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProtocolVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ProtocolVersion);
      }
      if (sample_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Sample);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProtocolVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ProtocolVersion);
      }
      if (sample_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Sample);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProtocolVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProtocolVersion);
      }
      if (sample_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Sample);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClientMovementPacket other) {
      if (other == null) {
        return;
      }
      if (other.ProtocolVersion != 0) {
        ProtocolVersion = other.ProtocolVersion;
      }
      if (other.sample_ != null) {
        if (sample_ == null) {
          Sample = new global::Dreamsleeve.Protocol.Chat.MovementSample();
        }
        Sample.MergeFrom(other.Sample);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProtocolVersion = input.ReadUInt32();
            break;
          }
          case 18: {
            if (sample_ == null) {
              Sample = new global::Dreamsleeve.Protocol.Chat.MovementSample();
            }
            input.ReadMessage(Sample);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProtocolVersion = input.ReadUInt32();
            break;
          }
          case 18: {
            if (sample_ == null) {
              Sample = new global::Dreamsleeve.Protocol.Chat.MovementSample();
            }
            input.ReadMessage(Sample);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ServerMovementPacket : pb::IMessage<ServerMovementPacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ServerMovementPacket> _parser = new pb::MessageParser<ServerMovementPacket>(() => new ServerMovementPacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ServerMovementPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dreamsleeve.Protocol.Chat.ProtocolReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMovementPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMovementPacket(ServerMovementPacket other) : this() {
      protocolVersion_ = other.protocolVersion_;
      movements_ = other.movements_ != null ? other.movements_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ServerMovementPacket Clone() {
      return new ServerMovementPacket(this);
    }

    /// <summary>Field number for the "protocol_version" field.</summary>
    public const int ProtocolVersionFieldNumber = 1;
    private uint protocolVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ProtocolVersion {
      get { return protocolVersion_; }
      set {
        protocolVersion_ = value;
      }
    }

    /// <summary>Field number for the "movements" field.</summary>
    public const int MovementsFieldNumber = 2;
    private global::Dreamsleeve.Protocol.Chat.PlayersMoved movements_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dreamsleeve.Protocol.Chat.PlayersMoved Movements {
      get { return movements_; }
      set {
        movements_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ServerMovementPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ServerMovementPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProtocolVersion != other.ProtocolVersion) return false;
      if (!object.Equals(Movements, other.Movements)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProtocolVersion != 0) hash ^= ProtocolVersion.GetHashCode();
      if (movements_ != null) hash ^= Movements.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProtocolVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ProtocolVersion);
      }
      if (movements_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Movements);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProtocolVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ProtocolVersion);
      }
      if (movements_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Movements);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProtocolVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProtocolVersion);
      }
      if (movements_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Movements);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ServerMovementPacket other) {
      if (other == null) {
        return;
      }
      if (other.ProtocolVersion != 0) {
        ProtocolVersion = other.ProtocolVersion;
      }
      if (other.movements_ != null) {
        if (movements_ == null) {
          Movements = new global::Dreamsleeve.Protocol.Chat.PlayersMoved();
        }
        Movements.MergeFrom(other.Movements);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProtocolVersion = input.ReadUInt32();
            break;
          }
          case 18: {
            if (movements_ == null) {
              Movements = new global::Dreamsleeve.Protocol.Chat.PlayersMoved();
            }
            input.ReadMessage(Movements);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProtocolVersion = input.ReadUInt32();
            break;
          }
          case 18: {
            if (movements_ == null) {
              Movements = new global::Dreamsleeve.Protocol.Chat.PlayersMoved();
            }
            input.ReadMessage(Movements);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
