// Generated by Scripts/generate_protocol.py from protoc C++ output. Do not edit.
// MSVC cannot emit an IFC containing protobuf headers; see docs/MsvcProtobufModulesRu.md.
export module Dreamsleeve.Protocol;

import std;

export namespace Protocol::Network
{

  enum class DisconnectReason : std::uint32_t
  {
    Unspecified    = 0,
    ClientShutdown = 1,
    ServerShutdown = 2,
    Kicked         = 3,
    AuthFailed     = 4,
    TimeoutPolicy  = 5,
    ProtocolError  = 6,
  };

}

export namespace Protocol::Chat
{

  enum class RequestRejectionCode : std::int32_t
  {
    Unspecified        = 0,
    InvalidRequest     = 1,
    SessionNotReady    = 2,
    SessionAlreadyOpen = 3,
    UsernameTaken      = 4,
    ChannelNotFound    = 5,
    NotChannelMember   = 6,
  };

}
