// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: session.proto
// Protobuf C++ Version: 6.33.2

#ifndef session_2eproto_2epb_2eh
#define session_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "chat.pb.h"
#include "player.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_session_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_session_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_session_2eproto;
}  // extern "C"
namespace Dreamsleeve {
namespace Protocol {
namespace Chat {
enum HiddenIdentity : int;
extern const uint32_t HiddenIdentity_internal_data_[];
class ChangeDisplayName;
struct ChangeDisplayNameDefaultTypeInternal;
extern ChangeDisplayNameDefaultTypeInternal _ChangeDisplayName_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ChangeDisplayName_class_data_;
class DisplayNameChanged;
struct DisplayNameChangedDefaultTypeInternal;
extern DisplayNameChangedDefaultTypeInternal _DisplayNameChanged_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DisplayNameChanged_class_data_;
class IdentityVisibilityChanged;
struct IdentityVisibilityChangedDefaultTypeInternal;
extern IdentityVisibilityChangedDefaultTypeInternal _IdentityVisibilityChanged_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull IdentityVisibilityChanged_class_data_;
class OpenSession;
struct OpenSessionDefaultTypeInternal;
extern OpenSessionDefaultTypeInternal _OpenSession_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OpenSession_class_data_;
class SessionOpened;
struct SessionOpenedDefaultTypeInternal;
extern SessionOpenedDefaultTypeInternal _SessionOpened_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SessionOpened_class_data_;
class SetIdentityVisibility;
struct SetIdentityVisibilityDefaultTypeInternal;
extern SetIdentityVisibilityDefaultTypeInternal _SetIdentityVisibility_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SetIdentityVisibility_class_data_;
}  // namespace Chat
}  // namespace Protocol
}  // namespace Dreamsleeve
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::Dreamsleeve::Protocol::Chat::HiddenIdentity_internal_data_>
    internal::EnumTraitsImpl::value<::Dreamsleeve::Protocol::Chat::HiddenIdentity>;
}  // namespace protobuf
}  // namespace google

namespace Dreamsleeve {
namespace Protocol {
namespace Chat {
enum HiddenIdentity : int {
  HIDDEN_IDENTITY_NONE = 0,
  HIDDEN_IDENTITY_EVERYWHERE = 1,
  HIDDEN_IDENTITY_EXCEPT_GROUND_MARKS = 2,
  HiddenIdentity_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  HiddenIdentity_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t HiddenIdentity_internal_data_[];
inline constexpr HiddenIdentity HiddenIdentity_MIN =
    static_cast<HiddenIdentity>(0);
inline constexpr HiddenIdentity HiddenIdentity_MAX =
    static_cast<HiddenIdentity>(2);
inline bool HiddenIdentity_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int HiddenIdentity_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL HiddenIdentity_descriptor();
template <typename T>
const ::std::string& HiddenIdentity_Name(T value) {
  static_assert(::std::is_same<T, HiddenIdentity>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to HiddenIdentity_Name().");
  return HiddenIdentity_Name(static_cast<HiddenIdentity>(value));
}
template <>
inline const ::std::string& HiddenIdentity_Name(HiddenIdentity value) {
  return ::google::protobuf::internal::NameOfDenseEnum<HiddenIdentity_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool HiddenIdentity_Parse(
    ::absl::string_view name, HiddenIdentity* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<HiddenIdentity>(HiddenIdentity_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class SetIdentityVisibility final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Dreamsleeve.Protocol.Chat.SetIdentityVisibility) */ {
 public:
  inline SetIdentityVisibility() : SetIdentityVisibility(nullptr) {}
  ~SetIdentityVisibility() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SetIdentityVisibility* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SetIdentityVisibility));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SetIdentityVisibility(::google::protobuf::internal::ConstantInitialized);

  inline SetIdentityVisibility(const SetIdentityVisibility& from) : SetIdentityVisibility(nullptr, from) {}
  inline SetIdentityVisibility(SetIdentityVisibility&& from) noexcept
      : SetIdentityVisibility(nullptr, ::std::move(from)) {}
  inline SetIdentityVisibility& operator=(const SetIdentityVisibility& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetIdentityVisibility& operator=(SetIdentityVisibility&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetIdentityVisibility& default_instance() {
    return *reinterpret_cast<const SetIdentityVisibility*>(
        &_SetIdentityVisibility_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SetIdentityVisibility& a, SetIdentityVisibility& b) { a.Swap(&b); }
  inline void Swap(SetIdentityVisibility* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetIdentityVisibility* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetIdentityVisibility* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SetIdentityVisibility>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SetIdentityVisibility& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SetIdentityVisibility& from) { SetIdentityVisibility::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SetIdentityVisibility* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Dreamsleeve.Protocol.Chat.SetIdentityVisibility"; }

  explicit SetIdentityVisibility(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SetIdentityVisibility(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SetIdentityVisibility& from);
  SetIdentityVisibility(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SetIdentityVisibility&& from) noexcept
      : SetIdentityVisibility(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHiddenFieldNumber = 1,
  };
  // .Dreamsleeve.Protocol.Chat.HiddenIdentity hidden = 1;
  void clear_hidden() ;
  ::Dreamsleeve::Protocol::Chat::HiddenIdentity hidden() const;
  void set_hidden(::Dreamsleeve::Protocol::Chat::HiddenIdentity value);

  private:
  ::Dreamsleeve::Protocol::Chat::HiddenIdentity _internal_hidden() const;
  void _internal_set_hidden(::Dreamsleeve::Protocol::Chat::HiddenIdentity value);

  public:
  // @@protoc_insertion_point(class_scope:Dreamsleeve.Protocol.Chat.SetIdentityVisibility)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SetIdentityVisibility& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int hidden_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_session_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SetIdentityVisibility_class_data_;
// -------------------------------------------------------------------

class OpenSession final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Dreamsleeve.Protocol.Chat.OpenSession) */ {
 public:
  inline OpenSession() : OpenSession(nullptr) {}
  ~OpenSession() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OpenSession* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OpenSession));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OpenSession(::google::protobuf::internal::ConstantInitialized);

  inline OpenSession(const OpenSession& from) : OpenSession(nullptr, from) {}
  inline OpenSession(OpenSession&& from) noexcept
      : OpenSession(nullptr, ::std::move(from)) {}
  inline OpenSession& operator=(const OpenSession& from) {
    CopyFrom(from);
    return *this;
  }
  inline OpenSession& operator=(OpenSession&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OpenSession& default_instance() {
    return *reinterpret_cast<const OpenSession*>(
        &_OpenSession_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(OpenSession& a, OpenSession& b) { a.Swap(&b); }
  inline void Swap(OpenSession* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OpenSession* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OpenSession* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OpenSession>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OpenSession& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OpenSession& from) { OpenSession::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OpenSession* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Dreamsleeve.Protocol.Chat.OpenSession"; }

  explicit OpenSession(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OpenSession(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OpenSession& from);
  OpenSession(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OpenSession&& from) noexcept
      : OpenSession(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionTicketFieldNumber = 3,
    kHiddenIdentityFieldNumber = 4,
  };
  // string session_ticket = 3;
  void clear_session_ticket() ;
  const ::std::string& session_ticket() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_session_ticket(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_session_ticket();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_session_ticket();
  void set_allocated_session_ticket(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_session_ticket() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_session_ticket(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_session_ticket();

  public:
  // .Dreamsleeve.Protocol.Chat.HiddenIdentity hidden_identity = 4;
  void clear_hidden_identity() ;
  ::Dreamsleeve::Protocol::Chat::HiddenIdentity hidden_identity() const;
  void set_hidden_identity(::Dreamsleeve::Protocol::Chat::HiddenIdentity value);

  private:
  ::Dreamsleeve::Protocol::Chat::HiddenIdentity _internal_hidden_identity() const;
  void _internal_set_hidden_identity(::Dreamsleeve::Protocol::Chat::HiddenIdentity value);

  public:
  // @@protoc_insertion_point(class_scope:Dreamsleeve.Protocol.Chat.OpenSession)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 60,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OpenSession& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr session_ticket_;
    int hidden_identity_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_session_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OpenSession_class_data_;
// -------------------------------------------------------------------

class IdentityVisibilityChanged final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Dreamsleeve.Protocol.Chat.IdentityVisibilityChanged) */ {
 public:
  inline IdentityVisibilityChanged() : IdentityVisibilityChanged(nullptr) {}
  ~IdentityVisibilityChanged() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(IdentityVisibilityChanged* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(IdentityVisibilityChanged));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR IdentityVisibilityChanged(::google::protobuf::internal::ConstantInitialized);

  inline IdentityVisibilityChanged(const IdentityVisibilityChanged& from) : IdentityVisibilityChanged(nullptr, from) {}
  inline IdentityVisibilityChanged(IdentityVisibilityChanged&& from) noexcept
      : IdentityVisibilityChanged(nullptr, ::std::move(from)) {}
  inline IdentityVisibilityChanged& operator=(const IdentityVisibilityChanged& from) {
    CopyFrom(from);
    return *this;
  }
  inline IdentityVisibilityChanged& operator=(IdentityVisibilityChanged&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IdentityVisibilityChanged& default_instance() {
    return *reinterpret_cast<const IdentityVisibilityChanged*>(
        &_IdentityVisibilityChanged_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(IdentityVisibilityChanged& a, IdentityVisibilityChanged& b) { a.Swap(&b); }
  inline void Swap(IdentityVisibilityChanged* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IdentityVisibilityChanged* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IdentityVisibilityChanged* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<IdentityVisibilityChanged>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const IdentityVisibilityChanged& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const IdentityVisibilityChanged& from) { IdentityVisibilityChanged::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(IdentityVisibilityChanged* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Dreamsleeve.Protocol.Chat.IdentityVisibilityChanged"; }

  explicit IdentityVisibilityChanged(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  IdentityVisibilityChanged(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const IdentityVisibilityChanged& from);
  IdentityVisibilityChanged(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, IdentityVisibilityChanged&& from) noexcept
      : IdentityVisibilityChanged(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPseudonymFieldNumber = 1,
    kHiddenFieldNumber = 2,
  };
  // optional string pseudonym = 1;
  bool has_pseudonym() const;
  void clear_pseudonym() ;
  const ::std::string& pseudonym() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pseudonym(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pseudonym();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pseudonym();
  void set_allocated_pseudonym(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pseudonym() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pseudonym(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pseudonym();

  public:
  // .Dreamsleeve.Protocol.Chat.HiddenIdentity hidden = 2;
  void clear_hidden() ;
  ::Dreamsleeve::Protocol::Chat::HiddenIdentity hidden() const;
  void set_hidden(::Dreamsleeve::Protocol::Chat::HiddenIdentity value);

  private:
  ::Dreamsleeve::Protocol::Chat::HiddenIdentity _internal_hidden() const;
  void _internal_set_hidden(::Dreamsleeve::Protocol::Chat::HiddenIdentity value);

  public:
  // @@protoc_insertion_point(class_scope:Dreamsleeve.Protocol.Chat.IdentityVisibilityChanged)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 69,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const IdentityVisibilityChanged& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr pseudonym_;
    int hidden_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_session_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull IdentityVisibilityChanged_class_data_;
// -------------------------------------------------------------------

class DisplayNameChanged final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Dreamsleeve.Protocol.Chat.DisplayNameChanged) */ {
 public:
  inline DisplayNameChanged() : DisplayNameChanged(nullptr) {}
  ~DisplayNameChanged() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DisplayNameChanged* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DisplayNameChanged));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DisplayNameChanged(::google::protobuf::internal::ConstantInitialized);

  inline DisplayNameChanged(const DisplayNameChanged& from) : DisplayNameChanged(nullptr, from) {}
  inline DisplayNameChanged(DisplayNameChanged&& from) noexcept
      : DisplayNameChanged(nullptr, ::std::move(from)) {}
  inline DisplayNameChanged& operator=(const DisplayNameChanged& from) {
    CopyFrom(from);
    return *this;
  }
  inline DisplayNameChanged& operator=(DisplayNameChanged&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DisplayNameChanged& default_instance() {
    return *reinterpret_cast<const DisplayNameChanged*>(
        &_DisplayNameChanged_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(DisplayNameChanged& a, DisplayNameChanged& b) { a.Swap(&b); }
  inline void Swap(DisplayNameChanged* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DisplayNameChanged* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DisplayNameChanged* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DisplayNameChanged>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DisplayNameChanged& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DisplayNameChanged& from) { DisplayNameChanged::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DisplayNameChanged* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Dreamsleeve.Protocol.Chat.DisplayNameChanged"; }

  explicit DisplayNameChanged(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DisplayNameChanged(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DisplayNameChanged& from);
  DisplayNameChanged(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DisplayNameChanged&& from) noexcept
      : DisplayNameChanged(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDisplayNameFieldNumber = 1,
  };
  // string display_name = 1;
  void clear_display_name() ;
  const ::std::string& display_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_display_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_display_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_display_name();
  void set_allocated_display_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_display_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_display_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_display_name();

  public:
  // @@protoc_insertion_point(class_scope:Dreamsleeve.Protocol.Chat.DisplayNameChanged)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 65,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DisplayNameChanged& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr display_name_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_session_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DisplayNameChanged_class_data_;
// -------------------------------------------------------------------

class ChangeDisplayName final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Dreamsleeve.Protocol.Chat.ChangeDisplayName) */ {
 public:
  inline ChangeDisplayName() : ChangeDisplayName(nullptr) {}
  ~ChangeDisplayName() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ChangeDisplayName* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ChangeDisplayName));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ChangeDisplayName(::google::protobuf::internal::ConstantInitialized);

  inline ChangeDisplayName(const ChangeDisplayName& from) : ChangeDisplayName(nullptr, from) {}
  inline ChangeDisplayName(ChangeDisplayName&& from) noexcept
      : ChangeDisplayName(nullptr, ::std::move(from)) {}
  inline ChangeDisplayName& operator=(const ChangeDisplayName& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChangeDisplayName& operator=(ChangeDisplayName&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChangeDisplayName& default_instance() {
    return *reinterpret_cast<const ChangeDisplayName*>(
        &_ChangeDisplayName_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(ChangeDisplayName& a, ChangeDisplayName& b) { a.Swap(&b); }
  inline void Swap(ChangeDisplayName* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChangeDisplayName* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChangeDisplayName* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ChangeDisplayName>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ChangeDisplayName& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ChangeDisplayName& from) { ChangeDisplayName::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ChangeDisplayName* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Dreamsleeve.Protocol.Chat.ChangeDisplayName"; }

  explicit ChangeDisplayName(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ChangeDisplayName(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ChangeDisplayName& from);
  ChangeDisplayName(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ChangeDisplayName&& from) noexcept
      : ChangeDisplayName(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDisplayNameFieldNumber = 1,
  };
  // string display_name = 1;
  void clear_display_name() ;
  const ::std::string& display_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_display_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_display_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_display_name();
  void set_allocated_display_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_display_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_display_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_display_name();

  public:
  // @@protoc_insertion_point(class_scope:Dreamsleeve.Protocol.Chat.ChangeDisplayName)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 64,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ChangeDisplayName& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr display_name_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_session_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ChangeDisplayName_class_data_;
// -------------------------------------------------------------------

class SessionOpened final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Dreamsleeve.Protocol.Chat.SessionOpened) */ {
 public:
  inline SessionOpened() : SessionOpened(nullptr) {}
  ~SessionOpened() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SessionOpened* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SessionOpened));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SessionOpened(::google::protobuf::internal::ConstantInitialized);

  inline SessionOpened(const SessionOpened& from) : SessionOpened(nullptr, from) {}
  inline SessionOpened(SessionOpened&& from) noexcept
      : SessionOpened(nullptr, ::std::move(from)) {}
  inline SessionOpened& operator=(const SessionOpened& from) {
    CopyFrom(from);
    return *this;
  }
  inline SessionOpened& operator=(SessionOpened&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SessionOpened& default_instance() {
    return *reinterpret_cast<const SessionOpened*>(
        &_SessionOpened_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SessionOpened& a, SessionOpened& b) { a.Swap(&b); }
  inline void Swap(SessionOpened* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SessionOpened* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SessionOpened* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SessionOpened>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SessionOpened& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SessionOpened& from) { SessionOpened::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SessionOpened* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Dreamsleeve.Protocol.Chat.SessionOpened"; }

  explicit SessionOpened(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SessionOpened(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SessionOpened& from);
  SessionOpened(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SessionOpened&& from) noexcept
      : SessionOpened(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayersFieldNumber = 5,
    kChannelsFieldNumber = 8,
    kServerNameFieldNumber = 6,
    kOwnPseudonymFieldNumber = 9,
    kAnnouncementsFieldNumber = 7,
    kSelfPlayerIdFieldNumber = 1,
    kHiddenIdentityFieldNumber = 10,
  };
  // repeated .Dreamsleeve.Protocol.Chat.PlayerInfo players = 5;
  int players_size() const;
  private:
  int _internal_players_size() const;

  public:
  void clear_players() ;
  ::Dreamsleeve::Protocol::Chat::PlayerInfo* PROTOBUF_NONNULL mutable_players(int index);
  ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>* PROTOBUF_NONNULL mutable_players();

  private:
  const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>& _internal_players() const;
  ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>* PROTOBUF_NONNULL _internal_mutable_players();
  public:
  const ::Dreamsleeve::Protocol::Chat::PlayerInfo& players(int index) const;
  ::Dreamsleeve::Protocol::Chat::PlayerInfo* PROTOBUF_NONNULL add_players();
  const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>& players() const;
  // repeated .Dreamsleeve.Protocol.Chat.ChatChannel channels = 8;
  int channels_size() const;
  private:
  int _internal_channels_size() const;

  public:
  void clear_channels() ;
  ::Dreamsleeve::Protocol::Chat::ChatChannel* PROTOBUF_NONNULL mutable_channels(int index);
  ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>* PROTOBUF_NONNULL mutable_channels();

  private:
  const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>& _internal_channels() const;
  ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>* PROTOBUF_NONNULL _internal_mutable_channels();
  public:
  const ::Dreamsleeve::Protocol::Chat::ChatChannel& channels(int index) const;
  ::Dreamsleeve::Protocol::Chat::ChatChannel* PROTOBUF_NONNULL add_channels();
  const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>& channels() const;
  // string server_name = 6;
  void clear_server_name() ;
  const ::std::string& server_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_server_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_server_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_server_name();
  void set_allocated_server_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_server_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_server_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_server_name();

  public:
  // optional string own_pseudonym = 9;
  bool has_own_pseudonym() const;
  void clear_own_pseudonym() ;
  const ::std::string& own_pseudonym() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_own_pseudonym(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_own_pseudonym();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_own_pseudonym();
  void set_allocated_own_pseudonym(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_own_pseudonym() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_own_pseudonym(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_own_pseudonym();

  public:
  // .Dreamsleeve.Protocol.Chat.AnnouncementPolicy announcements = 7;
  bool has_announcements() const;
  void clear_announcements() ;
  const ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy& announcements() const;
  [[nodiscard]] ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE release_announcements();
  ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NONNULL mutable_announcements();
  void set_allocated_announcements(::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_announcements(::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE value);
  ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE unsafe_arena_release_announcements();

  private:
  const ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy& _internal_announcements() const;
  ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NONNULL _internal_mutable_announcements();

  public:
  // uint64 self_player_id = 1;
  void clear_self_player_id() ;
  ::uint64_t self_player_id() const;
  void set_self_player_id(::uint64_t value);

  private:
  ::uint64_t _internal_self_player_id() const;
  void _internal_set_self_player_id(::uint64_t value);

  public:
  // .Dreamsleeve.Protocol.Chat.HiddenIdentity hidden_identity = 10;
  void clear_hidden_identity() ;
  ::Dreamsleeve::Protocol::Chat::HiddenIdentity hidden_identity() const;
  void set_hidden_identity(::Dreamsleeve::Protocol::Chat::HiddenIdentity value);

  private:
  ::Dreamsleeve::Protocol::Chat::HiddenIdentity _internal_hidden_identity() const;
  void _internal_set_hidden_identity(::Dreamsleeve::Protocol::Chat::HiddenIdentity value);

  public:
  // @@protoc_insertion_point(class_scope:Dreamsleeve.Protocol.Chat.SessionOpened)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   3, 72,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SessionOpened& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::Dreamsleeve::Protocol::Chat::PlayerInfo > players_;
    ::google::protobuf::RepeatedPtrField< ::Dreamsleeve::Protocol::Chat::ChatChannel > channels_;
    ::google::protobuf::internal::ArenaStringPtr server_name_;
    ::google::protobuf::internal::ArenaStringPtr own_pseudonym_;
    ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE announcements_;
    ::uint64_t self_player_id_;
    int hidden_identity_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_session_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SessionOpened_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// OpenSession

// string session_ticket = 3;
inline void OpenSession::clear_session_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_ticket_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& OpenSession::session_ticket() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.OpenSession.session_ticket)
  return _internal_session_ticket();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void OpenSession::set_session_ticket(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.session_ticket_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.OpenSession.session_ticket)
}
inline ::std::string* PROTOBUF_NONNULL OpenSession::mutable_session_ticket()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_session_ticket();
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.OpenSession.session_ticket)
  return _s;
}
inline const ::std::string& OpenSession::_internal_session_ticket() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_ticket_.Get();
}
inline void OpenSession::_internal_set_session_ticket(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_ticket_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL OpenSession::_internal_mutable_session_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.session_ticket_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE OpenSession::release_session_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dreamsleeve.Protocol.Chat.OpenSession.session_ticket)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.session_ticket_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.session_ticket_.Set("", GetArena());
  }
  return released;
}
inline void OpenSession::set_allocated_session_ticket(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.session_ticket_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_ticket_.IsDefault()) {
    _impl_.session_ticket_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Dreamsleeve.Protocol.Chat.OpenSession.session_ticket)
}

// .Dreamsleeve.Protocol.Chat.HiddenIdentity hidden_identity = 4;
inline void OpenSession::clear_hidden_identity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hidden_identity_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::Dreamsleeve::Protocol::Chat::HiddenIdentity OpenSession::hidden_identity() const {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.OpenSession.hidden_identity)
  return _internal_hidden_identity();
}
inline void OpenSession::set_hidden_identity(::Dreamsleeve::Protocol::Chat::HiddenIdentity value) {
  _internal_set_hidden_identity(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.OpenSession.hidden_identity)
}
inline ::Dreamsleeve::Protocol::Chat::HiddenIdentity OpenSession::_internal_hidden_identity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Dreamsleeve::Protocol::Chat::HiddenIdentity>(_impl_.hidden_identity_);
}
inline void OpenSession::_internal_set_hidden_identity(::Dreamsleeve::Protocol::Chat::HiddenIdentity value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hidden_identity_ = value;
}

// -------------------------------------------------------------------

// SessionOpened

// string server_name = 6;
inline void SessionOpened::clear_server_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& SessionOpened::server_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SessionOpened.server_name)
  return _internal_server_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SessionOpened::set_server_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.server_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.SessionOpened.server_name)
}
inline ::std::string* PROTOBUF_NONNULL SessionOpened::mutable_server_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_server_name();
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.SessionOpened.server_name)
  return _s;
}
inline const ::std::string& SessionOpened::_internal_server_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.server_name_.Get();
}
inline void SessionOpened::_internal_set_server_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SessionOpened::_internal_mutable_server_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.server_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SessionOpened::release_server_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dreamsleeve.Protocol.Chat.SessionOpened.server_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.server_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.server_name_.Set("", GetArena());
  }
  return released;
}
inline void SessionOpened::set_allocated_server_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.server_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.server_name_.IsDefault()) {
    _impl_.server_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Dreamsleeve.Protocol.Chat.SessionOpened.server_name)
}

// uint64 self_player_id = 1;
inline void SessionOpened::clear_self_player_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.self_player_id_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint64_t SessionOpened::self_player_id() const {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SessionOpened.self_player_id)
  return _internal_self_player_id();
}
inline void SessionOpened::set_self_player_id(::uint64_t value) {
  _internal_set_self_player_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.SessionOpened.self_player_id)
}
inline ::uint64_t SessionOpened::_internal_self_player_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.self_player_id_;
}
inline void SessionOpened::_internal_set_self_player_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.self_player_id_ = value;
}

// repeated .Dreamsleeve.Protocol.Chat.PlayerInfo players = 5;
inline int SessionOpened::_internal_players_size() const {
  return _internal_players().size();
}
inline int SessionOpened::players_size() const {
  return _internal_players_size();
}
inline ::Dreamsleeve::Protocol::Chat::PlayerInfo* PROTOBUF_NONNULL SessionOpened::mutable_players(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.SessionOpened.players)
  return _internal_mutable_players()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>* PROTOBUF_NONNULL SessionOpened::mutable_players()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:Dreamsleeve.Protocol.Chat.SessionOpened.players)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_players();
}
inline const ::Dreamsleeve::Protocol::Chat::PlayerInfo& SessionOpened::players(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SessionOpened.players)
  return _internal_players().Get(index);
}
inline ::Dreamsleeve::Protocol::Chat::PlayerInfo* PROTOBUF_NONNULL SessionOpened::add_players()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Dreamsleeve::Protocol::Chat::PlayerInfo* _add =
      _internal_mutable_players()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:Dreamsleeve.Protocol.Chat.SessionOpened.players)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>& SessionOpened::players() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Dreamsleeve.Protocol.Chat.SessionOpened.players)
  return _internal_players();
}
inline const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>&
SessionOpened::_internal_players() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.players_;
}
inline ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>* PROTOBUF_NONNULL
SessionOpened::_internal_mutable_players() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.players_;
}

// .Dreamsleeve.Protocol.Chat.AnnouncementPolicy announcements = 7;
inline bool SessionOpened::has_announcements() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  PROTOBUF_ASSUME(!value || _impl_.announcements_ != nullptr);
  return value;
}
inline const ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy& SessionOpened::_internal_announcements() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* p = _impl_.announcements_;
  return p != nullptr ? *p : reinterpret_cast<const ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy&>(::Dreamsleeve::Protocol::Chat::_AnnouncementPolicy_default_instance_);
}
inline const ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy& SessionOpened::announcements() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SessionOpened.announcements)
  return _internal_announcements();
}
inline void SessionOpened::unsafe_arena_set_allocated_announcements(
    ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.announcements_);
  }
  _impl_.announcements_ = reinterpret_cast<::Dreamsleeve::Protocol::Chat::AnnouncementPolicy*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Dreamsleeve.Protocol.Chat.SessionOpened.announcements)
}
inline ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE SessionOpened::release_announcements() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* released = _impl_.announcements_;
  _impl_.announcements_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE SessionOpened::unsafe_arena_release_announcements() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dreamsleeve.Protocol.Chat.SessionOpened.announcements)

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* temp = _impl_.announcements_;
  _impl_.announcements_ = nullptr;
  return temp;
}
inline ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NONNULL SessionOpened::_internal_mutable_announcements() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.announcements_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Dreamsleeve::Protocol::Chat::AnnouncementPolicy>(GetArena());
    _impl_.announcements_ = reinterpret_cast<::Dreamsleeve::Protocol::Chat::AnnouncementPolicy*>(p);
  }
  return _impl_.announcements_;
}
inline ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NONNULL SessionOpened::mutable_announcements()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* _msg = _internal_mutable_announcements();
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.SessionOpened.announcements)
  return _msg;
}
inline void SessionOpened::set_allocated_announcements(::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.announcements_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }

  _impl_.announcements_ = reinterpret_cast<::Dreamsleeve::Protocol::Chat::AnnouncementPolicy*>(value);
  // @@protoc_insertion_point(field_set_allocated:Dreamsleeve.Protocol.Chat.SessionOpened.announcements)
}

// repeated .Dreamsleeve.Protocol.Chat.ChatChannel channels = 8;
inline int SessionOpened::_internal_channels_size() const {
  return _internal_channels().size();
}
inline int SessionOpened::channels_size() const {
  return _internal_channels_size();
}
inline ::Dreamsleeve::Protocol::Chat::ChatChannel* PROTOBUF_NONNULL SessionOpened::mutable_channels(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.SessionOpened.channels)
  return _internal_mutable_channels()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>* PROTOBUF_NONNULL SessionOpened::mutable_channels()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:Dreamsleeve.Protocol.Chat.SessionOpened.channels)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_channels();
}
inline const ::Dreamsleeve::Protocol::Chat::ChatChannel& SessionOpened::channels(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SessionOpened.channels)
  return _internal_channels().Get(index);
}
inline ::Dreamsleeve::Protocol::Chat::ChatChannel* PROTOBUF_NONNULL SessionOpened::add_channels()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Dreamsleeve::Protocol::Chat::ChatChannel* _add =
      _internal_mutable_channels()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:Dreamsleeve.Protocol.Chat.SessionOpened.channels)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>& SessionOpened::channels() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Dreamsleeve.Protocol.Chat.SessionOpened.channels)
  return _internal_channels();
}
inline const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>&
SessionOpened::_internal_channels() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.channels_;
}
inline ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>* PROTOBUF_NONNULL
SessionOpened::_internal_mutable_channels() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.channels_;
}

// optional string own_pseudonym = 9;
inline bool SessionOpened::has_own_pseudonym() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void SessionOpened::clear_own_pseudonym() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.own_pseudonym_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& SessionOpened::own_pseudonym() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SessionOpened.own_pseudonym)
  return _internal_own_pseudonym();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SessionOpened::set_own_pseudonym(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.own_pseudonym_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.SessionOpened.own_pseudonym)
}
inline ::std::string* PROTOBUF_NONNULL SessionOpened::mutable_own_pseudonym()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_own_pseudonym();
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.SessionOpened.own_pseudonym)
  return _s;
}
inline const ::std::string& SessionOpened::_internal_own_pseudonym() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.own_pseudonym_.Get();
}
inline void SessionOpened::_internal_set_own_pseudonym(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.own_pseudonym_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SessionOpened::_internal_mutable_own_pseudonym() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.own_pseudonym_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SessionOpened::release_own_pseudonym() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dreamsleeve.Protocol.Chat.SessionOpened.own_pseudonym)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.own_pseudonym_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.own_pseudonym_.Set("", GetArena());
  }
  return released;
}
inline void SessionOpened::set_allocated_own_pseudonym(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.own_pseudonym_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.own_pseudonym_.IsDefault()) {
    _impl_.own_pseudonym_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Dreamsleeve.Protocol.Chat.SessionOpened.own_pseudonym)
}

// .Dreamsleeve.Protocol.Chat.HiddenIdentity hidden_identity = 10;
inline void SessionOpened::clear_hidden_identity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hidden_identity_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::Dreamsleeve::Protocol::Chat::HiddenIdentity SessionOpened::hidden_identity() const {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SessionOpened.hidden_identity)
  return _internal_hidden_identity();
}
inline void SessionOpened::set_hidden_identity(::Dreamsleeve::Protocol::Chat::HiddenIdentity value) {
  _internal_set_hidden_identity(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.SessionOpened.hidden_identity)
}
inline ::Dreamsleeve::Protocol::Chat::HiddenIdentity SessionOpened::_internal_hidden_identity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Dreamsleeve::Protocol::Chat::HiddenIdentity>(_impl_.hidden_identity_);
}
inline void SessionOpened::_internal_set_hidden_identity(::Dreamsleeve::Protocol::Chat::HiddenIdentity value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hidden_identity_ = value;
}

// -------------------------------------------------------------------

// SetIdentityVisibility

// .Dreamsleeve.Protocol.Chat.HiddenIdentity hidden = 1;
inline void SetIdentityVisibility::clear_hidden() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hidden_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::Dreamsleeve::Protocol::Chat::HiddenIdentity SetIdentityVisibility::hidden() const {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SetIdentityVisibility.hidden)
  return _internal_hidden();
}
inline void SetIdentityVisibility::set_hidden(::Dreamsleeve::Protocol::Chat::HiddenIdentity value) {
  _internal_set_hidden(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.SetIdentityVisibility.hidden)
}
inline ::Dreamsleeve::Protocol::Chat::HiddenIdentity SetIdentityVisibility::_internal_hidden() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Dreamsleeve::Protocol::Chat::HiddenIdentity>(_impl_.hidden_);
}
inline void SetIdentityVisibility::_internal_set_hidden(::Dreamsleeve::Protocol::Chat::HiddenIdentity value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hidden_ = value;
}

// -------------------------------------------------------------------

// IdentityVisibilityChanged

// optional string pseudonym = 1;
inline bool IdentityVisibilityChanged::has_pseudonym() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void IdentityVisibilityChanged::clear_pseudonym() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pseudonym_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& IdentityVisibilityChanged::pseudonym() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.IdentityVisibilityChanged.pseudonym)
  return _internal_pseudonym();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void IdentityVisibilityChanged::set_pseudonym(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.pseudonym_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.IdentityVisibilityChanged.pseudonym)
}
inline ::std::string* PROTOBUF_NONNULL IdentityVisibilityChanged::mutable_pseudonym()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_pseudonym();
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.IdentityVisibilityChanged.pseudonym)
  return _s;
}
inline const ::std::string& IdentityVisibilityChanged::_internal_pseudonym() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pseudonym_.Get();
}
inline void IdentityVisibilityChanged::_internal_set_pseudonym(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pseudonym_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL IdentityVisibilityChanged::_internal_mutable_pseudonym() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.pseudonym_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE IdentityVisibilityChanged::release_pseudonym() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dreamsleeve.Protocol.Chat.IdentityVisibilityChanged.pseudonym)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.pseudonym_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pseudonym_.Set("", GetArena());
  }
  return released;
}
inline void IdentityVisibilityChanged::set_allocated_pseudonym(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.pseudonym_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pseudonym_.IsDefault()) {
    _impl_.pseudonym_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Dreamsleeve.Protocol.Chat.IdentityVisibilityChanged.pseudonym)
}

// .Dreamsleeve.Protocol.Chat.HiddenIdentity hidden = 2;
inline void IdentityVisibilityChanged::clear_hidden() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hidden_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::Dreamsleeve::Protocol::Chat::HiddenIdentity IdentityVisibilityChanged::hidden() const {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.IdentityVisibilityChanged.hidden)
  return _internal_hidden();
}
inline void IdentityVisibilityChanged::set_hidden(::Dreamsleeve::Protocol::Chat::HiddenIdentity value) {
  _internal_set_hidden(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.IdentityVisibilityChanged.hidden)
}
inline ::Dreamsleeve::Protocol::Chat::HiddenIdentity IdentityVisibilityChanged::_internal_hidden() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Dreamsleeve::Protocol::Chat::HiddenIdentity>(_impl_.hidden_);
}
inline void IdentityVisibilityChanged::_internal_set_hidden(::Dreamsleeve::Protocol::Chat::HiddenIdentity value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hidden_ = value;
}

// -------------------------------------------------------------------

// ChangeDisplayName

// string display_name = 1;
inline void ChangeDisplayName::clear_display_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.display_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& ChangeDisplayName::display_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.ChangeDisplayName.display_name)
  return _internal_display_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ChangeDisplayName::set_display_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.display_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.ChangeDisplayName.display_name)
}
inline ::std::string* PROTOBUF_NONNULL ChangeDisplayName::mutable_display_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_display_name();
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.ChangeDisplayName.display_name)
  return _s;
}
inline const ::std::string& ChangeDisplayName::_internal_display_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.display_name_.Get();
}
inline void ChangeDisplayName::_internal_set_display_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.display_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ChangeDisplayName::_internal_mutable_display_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.display_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ChangeDisplayName::release_display_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dreamsleeve.Protocol.Chat.ChangeDisplayName.display_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.display_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.display_name_.Set("", GetArena());
  }
  return released;
}
inline void ChangeDisplayName::set_allocated_display_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.display_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.display_name_.IsDefault()) {
    _impl_.display_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Dreamsleeve.Protocol.Chat.ChangeDisplayName.display_name)
}

// -------------------------------------------------------------------

// DisplayNameChanged

// string display_name = 1;
inline void DisplayNameChanged::clear_display_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.display_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& DisplayNameChanged::display_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.DisplayNameChanged.display_name)
  return _internal_display_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void DisplayNameChanged::set_display_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.display_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.DisplayNameChanged.display_name)
}
inline ::std::string* PROTOBUF_NONNULL DisplayNameChanged::mutable_display_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_display_name();
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.DisplayNameChanged.display_name)
  return _s;
}
inline const ::std::string& DisplayNameChanged::_internal_display_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.display_name_.Get();
}
inline void DisplayNameChanged::_internal_set_display_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.display_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL DisplayNameChanged::_internal_mutable_display_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.display_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE DisplayNameChanged::release_display_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dreamsleeve.Protocol.Chat.DisplayNameChanged.display_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.display_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.display_name_.Set("", GetArena());
  }
  return released;
}
inline void DisplayNameChanged::set_allocated_display_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.display_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.display_name_.IsDefault()) {
    _impl_.display_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Dreamsleeve.Protocol.Chat.DisplayNameChanged.display_name)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Chat
}  // namespace Protocol
}  // namespace Dreamsleeve


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Dreamsleeve::Protocol::Chat::HiddenIdentity> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Dreamsleeve::Protocol::Chat::HiddenIdentity>() {
  return ::Dreamsleeve::Protocol::Chat::HiddenIdentity_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // session_2eproto_2epb_2eh
