// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: session.proto
// Protobuf C++ Version: 6.33.2

#ifndef session_2eproto_2epb_2eh
#define session_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "chat.pb.h"
#include "player.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_session_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_session_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_session_2eproto;
}  // extern "C"
namespace Dreamsleeve {
namespace Protocol {
namespace Chat {
class OpenSession;
struct OpenSessionDefaultTypeInternal;
extern OpenSessionDefaultTypeInternal _OpenSession_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OpenSession_class_data_;
class SessionOpened;
struct SessionOpenedDefaultTypeInternal;
extern SessionOpenedDefaultTypeInternal _SessionOpened_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SessionOpened_class_data_;
}  // namespace Chat
}  // namespace Protocol
}  // namespace Dreamsleeve
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Dreamsleeve {
namespace Protocol {
namespace Chat {

// ===================================================================


// -------------------------------------------------------------------

class OpenSession final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Dreamsleeve.Protocol.Chat.OpenSession) */ {
 public:
  inline OpenSession() : OpenSession(nullptr) {}
  ~OpenSession() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OpenSession* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OpenSession));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OpenSession(::google::protobuf::internal::ConstantInitialized);

  inline OpenSession(const OpenSession& from) : OpenSession(nullptr, from) {}
  inline OpenSession(OpenSession&& from) noexcept
      : OpenSession(nullptr, ::std::move(from)) {}
  inline OpenSession& operator=(const OpenSession& from) {
    CopyFrom(from);
    return *this;
  }
  inline OpenSession& operator=(OpenSession&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OpenSession& default_instance() {
    return *reinterpret_cast<const OpenSession*>(
        &_OpenSession_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(OpenSession& a, OpenSession& b) { a.Swap(&b); }
  inline void Swap(OpenSession* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OpenSession* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OpenSession* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OpenSession>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OpenSession& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OpenSession& from) { OpenSession::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OpenSession* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Dreamsleeve.Protocol.Chat.OpenSession"; }

  explicit OpenSession(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OpenSession(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OpenSession& from);
  OpenSession(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OpenSession&& from) noexcept
      : OpenSession(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionTicketFieldNumber = 3,
  };
  // string session_ticket = 3;
  void clear_session_ticket() ;
  const ::std::string& session_ticket() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_session_ticket(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_session_ticket();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_session_ticket();
  void set_allocated_session_ticket(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_session_ticket() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_session_ticket(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_session_ticket();

  public:
  // @@protoc_insertion_point(class_scope:Dreamsleeve.Protocol.Chat.OpenSession)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 60,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OpenSession& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr session_ticket_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_session_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OpenSession_class_data_;
// -------------------------------------------------------------------

class SessionOpened final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Dreamsleeve.Protocol.Chat.SessionOpened) */ {
 public:
  inline SessionOpened() : SessionOpened(nullptr) {}
  ~SessionOpened() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SessionOpened* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SessionOpened));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SessionOpened(::google::protobuf::internal::ConstantInitialized);

  inline SessionOpened(const SessionOpened& from) : SessionOpened(nullptr, from) {}
  inline SessionOpened(SessionOpened&& from) noexcept
      : SessionOpened(nullptr, ::std::move(from)) {}
  inline SessionOpened& operator=(const SessionOpened& from) {
    CopyFrom(from);
    return *this;
  }
  inline SessionOpened& operator=(SessionOpened&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SessionOpened& default_instance() {
    return *reinterpret_cast<const SessionOpened*>(
        &_SessionOpened_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SessionOpened& a, SessionOpened& b) { a.Swap(&b); }
  inline void Swap(SessionOpened* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SessionOpened* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SessionOpened* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SessionOpened>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SessionOpened& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SessionOpened& from) { SessionOpened::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SessionOpened* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Dreamsleeve.Protocol.Chat.SessionOpened"; }

  explicit SessionOpened(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SessionOpened(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SessionOpened& from);
  SessionOpened(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SessionOpened&& from) noexcept
      : SessionOpened(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayersFieldNumber = 5,
    kChannelsFieldNumber = 8,
    kServerNameFieldNumber = 6,
    kAnnouncementsFieldNumber = 7,
    kSelfPlayerIdFieldNumber = 1,
  };
  // repeated .Dreamsleeve.Protocol.Chat.PlayerInfo players = 5;
  int players_size() const;
  private:
  int _internal_players_size() const;

  public:
  void clear_players() ;
  ::Dreamsleeve::Protocol::Chat::PlayerInfo* PROTOBUF_NONNULL mutable_players(int index);
  ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>* PROTOBUF_NONNULL mutable_players();

  private:
  const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>& _internal_players() const;
  ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>* PROTOBUF_NONNULL _internal_mutable_players();
  public:
  const ::Dreamsleeve::Protocol::Chat::PlayerInfo& players(int index) const;
  ::Dreamsleeve::Protocol::Chat::PlayerInfo* PROTOBUF_NONNULL add_players();
  const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>& players() const;
  // repeated .Dreamsleeve.Protocol.Chat.ChatChannel channels = 8;
  int channels_size() const;
  private:
  int _internal_channels_size() const;

  public:
  void clear_channels() ;
  ::Dreamsleeve::Protocol::Chat::ChatChannel* PROTOBUF_NONNULL mutable_channels(int index);
  ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>* PROTOBUF_NONNULL mutable_channels();

  private:
  const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>& _internal_channels() const;
  ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>* PROTOBUF_NONNULL _internal_mutable_channels();
  public:
  const ::Dreamsleeve::Protocol::Chat::ChatChannel& channels(int index) const;
  ::Dreamsleeve::Protocol::Chat::ChatChannel* PROTOBUF_NONNULL add_channels();
  const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>& channels() const;
  // string server_name = 6;
  void clear_server_name() ;
  const ::std::string& server_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_server_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_server_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_server_name();
  void set_allocated_server_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_server_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_server_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_server_name();

  public:
  // .Dreamsleeve.Protocol.Chat.AnnouncementPolicy announcements = 7;
  bool has_announcements() const;
  void clear_announcements() ;
  const ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy& announcements() const;
  [[nodiscard]] ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE release_announcements();
  ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NONNULL mutable_announcements();
  void set_allocated_announcements(::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_announcements(::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE value);
  ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE unsafe_arena_release_announcements();

  private:
  const ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy& _internal_announcements() const;
  ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NONNULL _internal_mutable_announcements();

  public:
  // uint64 self_player_id = 1;
  void clear_self_player_id() ;
  ::uint64_t self_player_id() const;
  void set_self_player_id(::uint64_t value);

  private:
  ::uint64_t _internal_self_player_id() const;
  void _internal_set_self_player_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Dreamsleeve.Protocol.Chat.SessionOpened)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   3, 59,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SessionOpened& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::Dreamsleeve::Protocol::Chat::PlayerInfo > players_;
    ::google::protobuf::RepeatedPtrField< ::Dreamsleeve::Protocol::Chat::ChatChannel > channels_;
    ::google::protobuf::internal::ArenaStringPtr server_name_;
    ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE announcements_;
    ::uint64_t self_player_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_session_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SessionOpened_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// OpenSession

// string session_ticket = 3;
inline void OpenSession::clear_session_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_ticket_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& OpenSession::session_ticket() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.OpenSession.session_ticket)
  return _internal_session_ticket();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void OpenSession::set_session_ticket(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.session_ticket_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.OpenSession.session_ticket)
}
inline ::std::string* PROTOBUF_NONNULL OpenSession::mutable_session_ticket()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_session_ticket();
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.OpenSession.session_ticket)
  return _s;
}
inline const ::std::string& OpenSession::_internal_session_ticket() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_ticket_.Get();
}
inline void OpenSession::_internal_set_session_ticket(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_ticket_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL OpenSession::_internal_mutable_session_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.session_ticket_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE OpenSession::release_session_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dreamsleeve.Protocol.Chat.OpenSession.session_ticket)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.session_ticket_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.session_ticket_.Set("", GetArena());
  }
  return released;
}
inline void OpenSession::set_allocated_session_ticket(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.session_ticket_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_ticket_.IsDefault()) {
    _impl_.session_ticket_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Dreamsleeve.Protocol.Chat.OpenSession.session_ticket)
}

// -------------------------------------------------------------------

// SessionOpened

// string server_name = 6;
inline void SessionOpened::clear_server_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& SessionOpened::server_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SessionOpened.server_name)
  return _internal_server_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SessionOpened::set_server_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.server_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.SessionOpened.server_name)
}
inline ::std::string* PROTOBUF_NONNULL SessionOpened::mutable_server_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_server_name();
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.SessionOpened.server_name)
  return _s;
}
inline const ::std::string& SessionOpened::_internal_server_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.server_name_.Get();
}
inline void SessionOpened::_internal_set_server_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SessionOpened::_internal_mutable_server_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.server_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SessionOpened::release_server_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dreamsleeve.Protocol.Chat.SessionOpened.server_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.server_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.server_name_.Set("", GetArena());
  }
  return released;
}
inline void SessionOpened::set_allocated_server_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.server_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.server_name_.IsDefault()) {
    _impl_.server_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Dreamsleeve.Protocol.Chat.SessionOpened.server_name)
}

// uint64 self_player_id = 1;
inline void SessionOpened::clear_self_player_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.self_player_id_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t SessionOpened::self_player_id() const {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SessionOpened.self_player_id)
  return _internal_self_player_id();
}
inline void SessionOpened::set_self_player_id(::uint64_t value) {
  _internal_set_self_player_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:Dreamsleeve.Protocol.Chat.SessionOpened.self_player_id)
}
inline ::uint64_t SessionOpened::_internal_self_player_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.self_player_id_;
}
inline void SessionOpened::_internal_set_self_player_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.self_player_id_ = value;
}

// repeated .Dreamsleeve.Protocol.Chat.PlayerInfo players = 5;
inline int SessionOpened::_internal_players_size() const {
  return _internal_players().size();
}
inline int SessionOpened::players_size() const {
  return _internal_players_size();
}
inline ::Dreamsleeve::Protocol::Chat::PlayerInfo* PROTOBUF_NONNULL SessionOpened::mutable_players(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.SessionOpened.players)
  return _internal_mutable_players()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>* PROTOBUF_NONNULL SessionOpened::mutable_players()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:Dreamsleeve.Protocol.Chat.SessionOpened.players)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_players();
}
inline const ::Dreamsleeve::Protocol::Chat::PlayerInfo& SessionOpened::players(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SessionOpened.players)
  return _internal_players().Get(index);
}
inline ::Dreamsleeve::Protocol::Chat::PlayerInfo* PROTOBUF_NONNULL SessionOpened::add_players()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Dreamsleeve::Protocol::Chat::PlayerInfo* _add =
      _internal_mutable_players()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:Dreamsleeve.Protocol.Chat.SessionOpened.players)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>& SessionOpened::players() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Dreamsleeve.Protocol.Chat.SessionOpened.players)
  return _internal_players();
}
inline const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>&
SessionOpened::_internal_players() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.players_;
}
inline ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::PlayerInfo>* PROTOBUF_NONNULL
SessionOpened::_internal_mutable_players() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.players_;
}

// .Dreamsleeve.Protocol.Chat.AnnouncementPolicy announcements = 7;
inline bool SessionOpened::has_announcements() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.announcements_ != nullptr);
  return value;
}
inline const ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy& SessionOpened::_internal_announcements() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* p = _impl_.announcements_;
  return p != nullptr ? *p : reinterpret_cast<const ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy&>(::Dreamsleeve::Protocol::Chat::_AnnouncementPolicy_default_instance_);
}
inline const ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy& SessionOpened::announcements() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SessionOpened.announcements)
  return _internal_announcements();
}
inline void SessionOpened::unsafe_arena_set_allocated_announcements(
    ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.announcements_);
  }
  _impl_.announcements_ = reinterpret_cast<::Dreamsleeve::Protocol::Chat::AnnouncementPolicy*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Dreamsleeve.Protocol.Chat.SessionOpened.announcements)
}
inline ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE SessionOpened::release_announcements() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* released = _impl_.announcements_;
  _impl_.announcements_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE SessionOpened::unsafe_arena_release_announcements() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Dreamsleeve.Protocol.Chat.SessionOpened.announcements)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* temp = _impl_.announcements_;
  _impl_.announcements_ = nullptr;
  return temp;
}
inline ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NONNULL SessionOpened::_internal_mutable_announcements() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.announcements_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Dreamsleeve::Protocol::Chat::AnnouncementPolicy>(GetArena());
    _impl_.announcements_ = reinterpret_cast<::Dreamsleeve::Protocol::Chat::AnnouncementPolicy*>(p);
  }
  return _impl_.announcements_;
}
inline ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NONNULL SessionOpened::mutable_announcements()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* _msg = _internal_mutable_announcements();
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.SessionOpened.announcements)
  return _msg;
}
inline void SessionOpened::set_allocated_announcements(::Dreamsleeve::Protocol::Chat::AnnouncementPolicy* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.announcements_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.announcements_ = reinterpret_cast<::Dreamsleeve::Protocol::Chat::AnnouncementPolicy*>(value);
  // @@protoc_insertion_point(field_set_allocated:Dreamsleeve.Protocol.Chat.SessionOpened.announcements)
}

// repeated .Dreamsleeve.Protocol.Chat.ChatChannel channels = 8;
inline int SessionOpened::_internal_channels_size() const {
  return _internal_channels().size();
}
inline int SessionOpened::channels_size() const {
  return _internal_channels_size();
}
inline ::Dreamsleeve::Protocol::Chat::ChatChannel* PROTOBUF_NONNULL SessionOpened::mutable_channels(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Dreamsleeve.Protocol.Chat.SessionOpened.channels)
  return _internal_mutable_channels()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>* PROTOBUF_NONNULL SessionOpened::mutable_channels()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:Dreamsleeve.Protocol.Chat.SessionOpened.channels)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_channels();
}
inline const ::Dreamsleeve::Protocol::Chat::ChatChannel& SessionOpened::channels(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Dreamsleeve.Protocol.Chat.SessionOpened.channels)
  return _internal_channels().Get(index);
}
inline ::Dreamsleeve::Protocol::Chat::ChatChannel* PROTOBUF_NONNULL SessionOpened::add_channels()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Dreamsleeve::Protocol::Chat::ChatChannel* _add =
      _internal_mutable_channels()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:Dreamsleeve.Protocol.Chat.SessionOpened.channels)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>& SessionOpened::channels() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Dreamsleeve.Protocol.Chat.SessionOpened.channels)
  return _internal_channels();
}
inline const ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>&
SessionOpened::_internal_channels() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.channels_;
}
inline ::google::protobuf::RepeatedPtrField<::Dreamsleeve::Protocol::Chat::ChatChannel>* PROTOBUF_NONNULL
SessionOpened::_internal_mutable_channels() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.channels_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Chat
}  // namespace Protocol
}  // namespace Dreamsleeve


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // session_2eproto_2epb_2eh
