<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Primitives.fs" />
        <Compile Include="Spatial.fs" />
        <Compile Include="ActorValues.fs" />
        <Compile Include="Players.fs" />
        <Compile Include="Chat.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.UMX" Version="1.1.0" />
    </ItemGroup>

</Project>
